### ISSUE TITLE
Add Objective Indicators to the HUD

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1003]
Author: @belst (belst)
Date: 2017-02-17
Redmine Issue: 1003, https://dev.etlegacy.com/issues/1003

---

Add directional objective indicators to the HUD.

Example from Dirty Bomb attached below.

---

Related issue(s): #481, #1000

---

Related commit(s):
f9d7c6a86a4e871262e2db2a1bf218886c0d130a - game: acivate G_ScriptAction_SetMainObjective / wm..
 d147d26f41678f278f351611513c393a0fb3a031 - cgame: paint the main objective given by mapper in..
 b07fb04ac8cab4878854a828599d17ba7cbce32e - mod: final fix for wm_set_main_objective script co..
 a22816ef86d26b104f67f1bb0ff16f3d23c15bd9 - game: fixed clang warning, refs 1003
 d3be5a795a21ffc343177ef08bb760ea775309f4 - game: allow all targetnames for wm_set_main_object..
 df99df556816825d46e4d5911fae493071ee157f - cgame: fixed command map objective icon color when..

**Comment by ETLegacyTeam** [comment]
From: @belst (belst)
Date: 2017-02-18T15:45:26Z

---

Icons are placeholder

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2017-02-18T16:48:00Z

---

I really like the concepts, belst, but it shows the frequently discussed problems of them. Those icons are very intrusive.
They should be easily toggleable to display or hide, depending on whether you know the map or not. Maybe through an entry in the "Game" menu tab.
The intrusiveness can be reduced by making them smaller and transparent and also removing the "Escort", "Repair" and distance labels.

I would also not display secondary objectives. For me the primary objective in Supply is the truck. Both the capture and the plant indicator should only be visible with direct line of sight, as they are rather secondary. Same as the CP in Goldrush. To say which objective is primary and therefore which indicator should be permanent requires a new script routine. Displaying the "cunstruct" indicator for the crane controls in Supply from the beginning, is not smart. It should only appear once the truck is in position. The mapper then has to put a ETL specific script routing behind the announcement "Truck is in position" , "protect the Gold" "blabla" to switch the primary indicator from Truck to Crane controls.

If all indicators are only displayed with direct line of sight, this script routine would not be necessary. However, we need to somehow tell the game which indicators are primary and should be displayed through walls. The same thing applies to limiting this to the compass, as spyhawk mentioned. Having the objective icons from the commandmap appear at the outer border of the compass, shows the direction they are at. They do not show the height difference though. To tell the game which icons to display at the border, we also need to tell the game which icons those are (a.k.a. which are primary).

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2017-02-18T16:54:27Z

---

//Second update to somewhat maintain read-ability.

What we could do is to have a look at the existign hints and make those show through walls. Pak0/gfx/2d/... DisarmHint, RepairHint, DynamiteHint,...
We could let the player choose which hints he wants displayed through walls and which not. DynamiteHint and DisarmHint are pretty straight forward, as those are usually crucial map-objectives. But we have no vehicle hint. (TankHint is for things that the tank shoots, like the Fueldump sewers grate). We also have no unique hint for stealable objectives like docs, radar parts, etc. Those use the regular usableHint. That one is also used by doors and what not.

Generally I like the idea of those indicators, but I can't really see how we can easily implement them, without a range of compromises.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-02-19T11:44:29Z

---

Using icons visible through wall is a bad idea, it's way too intrusive even optionally. There are issues in differentiating main and secondary objectives too - no way we'll provide additional scripts for all these maps.

Why not using the compass feature and the already provided code instead? The same way medic see revive icons on the compass, and the fieldops the "need ammo" icon, we can do the very same for engi/covops with the construct/destruct objectives. See the attached screenshots. I have enabled it for engineer - this is not a makeup, but actual working code.

* using compass means the icon is visible at 360 degrees, with direction relative to you.
* there is only planar view available, but if really needed we could work around it with some new icons/arrow to display the elevation.
* icons are bigger when close to the player, smaller when far away
* can be filtered by classes (construct and destruct for engi, only some of the destruct for covops, etc), or display some filter to all classes (see the command map existing filters)

It's not perfect, can become somewhat heavy in some situation (see last screenshot, with fireteam members icons also displayed), but it isn't bad either as the code uses a fading effect between filters and thus does not show everything at the same time.

We could also display icons over the objective (I like the idea), but these should be only visible when in sight. I don't see the use of icons visible through walls when the compass does the job in a better manner.

**Comment by ETLegacyTeam** [comment]
From: @realkemon (keMoN)
Date: 2017-02-19T12:28:28Z

---

I'm in favour of the combination of on-screen indicators when in direct line of sight (primary and secondary objectives) and the compass for permanent objective indicators.
The fireteam members should definitely have a different icon than objectives, otherwise it is going to be a mess.

But we still have the problem that we can't properly differentiate between primary and secondary objectives. Take Railgun for example. When the ammo is loaded onto the gun, the primary objective is to construct the gun controls. That is not a dynamite objective.
In my opinion we should provide the possibility for future mappers to set those indicators up properly. We don't need to create hundreds of files ourselves, but maybe there is a bored volunteer. And for our 'official' ETL maps, we could set them up properly. 

____________________________________________________________
I'd also like to make a suggestion for the second/alternative/minimalistic HUD:
Having the on-screen indicators in direct line of sight combined with compass indicators, makes the map inside the compass relatively redundant. In your example shots from oasis for example, the icon for the oasis wall is at the very top, because you are looking straight at it. However, in the map your player icon is looking right, because the map is fixated. Relying on the compass and on-screen indicators is entirely sufficient to get around in the map. Because of that, I would like to suggest a "flat compass thing":https://songbirdsings13.files.wordpress.com/2013/09/skyrim_field_of_view.jpg for the minimalistic HUD. Known from Skyrim, Fallout and many other RPGs.
Primary objectives, when not in line of sight of the player are displayed at the end of the bar, so the player knows he needs to turn around to see the objs. Player icons could be done like the enemy icons in this exampe, the diamond shaped thingies. Fireteam members could receive a different colour. Or you only display fireteam members there. 
Objectives can be displayed related to their style. Dynamite and pliers for example. Is it possible to display the disarm icon as primary objectives for defending engineers, once a dynamite has been planted? So they know where to go.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2017-03-03T11:41:24Z

---

{TODO}
* rework location system (add new display option?)
* use location distance? (system already exists but is unused)

See G_ScriptAction_SetMainObjective(), CS_MAIN_AXIS_OBJECTIVE and CS_MAIN_ALLIES_OBJECTIVE that are currently unused. We should use them!

**Comment by rmarquis** [comment]
Looking at the experimental implementation in newest nitmod: floating icons above objectives, that can be seen through walls but only on a relatively short distance only. It's much less intrusive, and one still needs to rely on the map (or compass) to get the right direction.

**Comment by rmarquis** [comment]
There is a regression in that last commit (84314f98120b77e132445ec2026edee94055a805). The player own icons are now displayed on the compass (for example own FT position, or objective icon when taking it), rather than being ignored.

**Comment by rmarquis** [comment]
At the risk of sounding hilariously stupid, do you mind describing what cg_drawEnvAwareness does here? I've tested it on and off and could literally not see any difference. Is the compass or HUD supposed to behave differently when this option is on? I couldn't infer it from the code either.

**Comment by Aranud** [comment]
It supposed to hide the HUD icons https://github.com/etlegacy/etlegacy/blob/8af6d96377dabc6e441140e51b6de094363d6465/src/cgame/cg_draw.c#L3764-L3767

**Comment by rmarquis** [comment]
Sorry, I really meant to say "which icons?" here. I can't see what this is about in regards to the above discussion (directional objective indicators).

**Comment by Aranud** [comment]
@rmarquis the above commit is now about objective indicators :)

**Comment by rmarquis** [comment]
Looks like the compass has significantly changed since I last played, so here's a few remarks, suggestions, ideas and complaints:


About Compass:

* **Teammate position is missing**. I actually quite make use of the white circles to quickly estimate where FT members are located relatively to you. If this removal is actually intentional, I'd suggest to show these only when the FT members are selected (the green triangle icon becomes red). FT selection only enables a few extra vsay, so there is barely any reason to use it as it is, and a more fined-grained display might also prove more useful than showing all FT members icons at all times.

* **Icons are hardly visible**. Using the actual icon of the objective makes it really hard to identify what that icon is. They are too detailled for the required small size, and it is hard to distinguish the type of objective from one to another. Instead, I'd suggest to use a simpler symbology for these icons, based on the action to be done (build, destroy) rather than the type. There are actually unused sprite icons in pak0 that perfectly fit this role: construct.tga (blue) and destroy.tga (red).

* **Some talk icons aren't relevant.** An engi doesn't need a red health icon displayed when a teammate ask for medpack, nor does a medic need an ammo icon when someone ask for ammo. Keep it relevant for the class, otherwise use the regular blue "!" talk icon. This is a vanilla issue.

* **It's way too noisy and doesn't focus on the essential.** Many secondary objectives aren't relevant to all classes (only some are, like capturable spawn), but primary objective certainly are (f.e. medic need to support engi so they can destroy the obj). Having a general direction towards the primary objective is useful, as this is where the bulk of action will take place. However, all primary objectives don't need to be displayed at all time, as further primary objective aren't relevant yet (f.e. the Old City Wall on Oasis, as opposed to the canons on the other side of the map). The game actually provides a way to distinguish the next primary objective, so display this icon only (on oasis: don't do display the canons until the wall is dynamited). Same as above, I'd make use of the unused symbol sprite icons for better clarity ("attack" and "defend" yellow icons on green background).

* **Add friendly artillery icon** too? It's been added on the map for everybody and is displayed for a few seconds before fading away. Having its relative position on the compass might be useful, as it display an immediate danger to the player.

* **Objective icons can't be turned off**, unlike drawEnv. I'd appreciate a cvar.

----
About DrawEnv:

I really really *hate* to be that guy, but I need to say the feature is barely usable. I want to love it, but I frankly heavily dislike as it is: as an engineer, the current implementation is way *too distracting*.

* **The icons placement in a circle in the center of the screen is no adequate.** It might make sense for an incoming nade (like NQ perk or some other modern games), but build/destroy objectives icon have way less priority than any immediate threat.
* **Icons pop in and out.** Because the icon isn't displayed if the objective is in the field of view, icons constantly pop in and out in a rather distracting and annoying way.

Contrast this with another recently implemented feature: the blood damage indicator. It's subtle, kinda discreet in the side your screen, yet highly efficient for gameplay purepose and a joy to have. That's the kind of feature I like to have, and I wish to move DrawEnv implementation towards that direction.

As a first step, I'd suggest
* to move drawEnv icons on the side of the sceen (like its done in so many other games). They'd still be visible, without taking you out of focus.
* implement floating icons above objectives like latest Nitmod does. If the objectives icons are displayed on the side of the screen, the transition when the objective is in the field of view would be more gradual and feel natural, without any distracting pop in effect.

Since there is some overlap with the compass, some remarks on compass might also apply here (icons visibility, relevance, ..) but I am not sure what the scope of DrawEnv is actually. Is it supposed to replicate all the compass information? Some suggestions above might be adequate here too.

Also found a small issue: when following a teammate while in limbo, the drawEnv hud show our class info rather than the teammeate info (f.e. build icons when following a medic).

Thoughts?

**Comment by rmarquis** [comment]
> Also found a small issue: when following a teammate while in limbo, the drawEnv hud show our class info rather than the teammeate info (f.e. build icons when following a medic).

DrawEnvAwareness has now the same visibility behaviour as the compass: it's hidden when following in limbo, and this bug isn't visible anymore. It might be worth fixing the underlying code for both compass and drawEnvAwareness later on, to make both visible when in limbo.

**Comment by Aranud** [comment]
> The icons placement in a circle in the center of the screen is no adequate. It might make sense for an incoming nade (like NQ perk or some other modern games), but build/destroy objectives icon have way less priority than any immediate threat.
    Icons pop in and out. Because the icon isn't displayed if the objective is in the field of view, icons constantly pop in and out in a rather distracting and annoying way.

Just to ensure we don't work on the same points, I'm doing this one :) 

Btw, nice feedback and so true.

**Comment by rmarquis** [comment]
All right, I'll focus on compass in the meantime. Reducing noise of all these icons is kinda convoluted, but we'll see what we can do.

**Comment by Aranud** [comment]
The icons in DrawEnvAwareness are fading away depending of the distance with the player. But the icons look barely visible on high fading, making the icons useless. 

As you suggest, we could follow what modern game do : displaying the distance (on close range ? middle range ? far range ?) instead of fading the icons.

Simple icons are needed too. The other HUD elements make difficult to track the icons.

**Comment by rmarquis** [comment]
> As you suggest, we could follow what modern game do : displaying the distance (on close range ? middle range ? far range ?) instead of fading the icons.

I'm actually wondering if it is wise to display objective icons that are really far away. These obj aren't immediately accessible, and their icons just clutter the screen/compass.

Maybe we should just display obj at medium/close range, and the player could always rely on the map to get the general direction of the far objectives to get closer, after which they'd be displayed on screen/compass. 

> Simple icons are needed too.

Yes, in any case I wouldn't reuse (or at least not reuse that much) hint icons to reduce confusion.

**Comment by rmarquis** [comment]
I'm testing simpler symbols with primary/secondary objectives, using the existing but unused pak0 icons (attack/defend/regroup, and blue/red respectively).
Spawns to be taken and primary objs are displayed to all classes, secondary to engi/covops only.

![2021-08-19-104924-oasis](https://user-images.githubusercontent.com/162442/130040069-175bacb2-910d-42d6-b3f8-e23d2a4b9e51.png)
![2021-08-19-105045-oasis](https://user-images.githubusercontent.com/162442/130040086-d97a36ce-019a-445f-805d-4e0b055604a1.png)
![2021-08-19-105313-oasis](https://user-images.githubusercontent.com/162442/130040099-3f73ac59-9f25-457f-9c51-76b325ae20f7.png)
![2021-08-19-105334-oasis](https://user-images.githubusercontent.com/162442/130040108-3ba6ea00-b687-4a30-86a2-0b679db05459.png)

**Comment by Aranud** [comment]
More lisible indeed. The defend / attack icons fit pretty fine.

I would recommand to use the defend icons when the flag poll is your (i.e the last screenshot with the axis  flag on but no icons set on top of it).
A bit redundant with the attack icon, but at least, it would indicate if it still capturable by the enemy or definitely acquired.

**Comment by Aranud** [comment]
Also I'm wondering if we should add the name / tips hint name / location of objectifs above the icons (i.e: old city wall / anti-tank fun, water pump, etc etc ...).
I'm afraid, it could take a lot place on the screen but I feel it could be usefull (if nicely handle), and toggleable.

**Comment by rmarquis** [comment]
> I would recommand to use the defend icons when the flag poll is your (i.e the last screenshot with the axis flag on but no icons set on top of it).

Good suggestion!

> Also I'm wondering if we should add the name / tips hint name / location of objectifs above the icons (i.e: old city wall / anti-tank fun, water pump, etc etc ...).

Do you mean for compass, or drawEnv? There isn't much space on compass, but it would fit nicely for drawEnv imho. In any case that's worth a try!

**Comment by rmarquis** [comment]
There are some issues with primary obj display on some map (f.e. radar, where the main door to be dynamited isn't shown), so I disabled that code for now while I investigate. For now, these icons will only be displayed to the relevant classes.
Icons have been updated as above (blue/red and green "actions" rather than shader type).

**Comment by Aranud** [comment]
I have removed the trace to check either or not the objective is behind a world element before drawing the icons. So the icon will be draw even if the objectif is visible. It will also save a lot ressource for this feature, there is no more trace computation.

The current distance is exprimed in unit. We could convert in meter and miles like the speedometer in HUD.

**Comment by rmarquis** [comment]
Do you have any idea why the floating icons are so... wobbly? It looks like they oscillate around the objective, instead of being fixed on it. That effect is quite disturbing.

I'd definitely make use the speedometer var to convert between meters, miles and game units!

**Comment by Aranud** [comment]
> Do you have any idea why the floating icons are so... wobbly? It looks like they oscillate around the objective, instead of being fixed on it. That effect is quite disturbing.

Will have a look. I think the position computation is so what wrong and should take into account the front distance.

> There are some issues with primary obj display on some map (f.e. radar, where the main door to be dynamited isn't shown), so I disabled that code for now while I investigate.

About this, OID entity (ET_OID_TRIGGER) are different from the entity catch to retrieve the icons (i.r ET_EXPLOSIVE_INDICATOR, ET_CONSTRUCTIBLE_INDICATOR, ET_TANK_INDICATOR, etc...)

Perhaps the origin could be the same, or trying to do a box trace and find the entity touching the OID could fo the trick.

**Comment by Aranud** [comment]
@rmarquis Found the issue with radar primary objectives. spawnflags is a bit mask used to indiquate primary objectives on OID trigger. Now it should work as expected and I have enable the "drawPrimaryObj".

In the same time, I have disable the objectives description. It work well ... but it took a lot space on the screen.

Perhaps we should display it if : 
* We are close enough ?
* The crosshair point the objective ?
* other ?

**Comment by rmarquis** [comment]
Fantastic work Ara! And you *also* fixed multi objective display, so f.e. both canon on oasis are displayed instead of only one.

Here are a few remarks that come to mind (TODO):
* the green/yellow icon on spawnflag seems to have its origin below ground, rather than on the flag. All the other obj icon seem properly located on the middle of the obj.
* icon on spawnflag seem to not always be displayed, depending on obstacle on the way(?). Might be related to the above.
* ~~I wouldn't display decimal when the distance is high (ie, instead of `75.4` we should use `75`, but short distance like `8.9` is okay). Maybe display the decimal only when it's below `10` or `20`.~~ (change to integer only, seems to be okay)
* ~~we might want to display distance unit too (`75 m`, `86 ft`, `35 u`) with `u` for "game unit".~~ (done, using `m` or `ft` or nothing for unit)
* ~~the revive icons displayed through walls are deemed too overpowered for use in comp, and I'd agree it gives an unfair advantage to those that use End Awarness even in public play. Probably use the indicators only for static objectives here?~~
* add friendly artillery icon on compass/awarness indicator too
* add obj icons on Objective menu in replacement/addition of team flags

I am not sure about the obj description implementation, but I guess it could be useful to get the name displayed even at high distance. So as a first step, maybe display the name when the crosshair point on it?

**Comment by rmarquis** [comment]
For 2.78, I think we just need a client cvar to hide the objective icons that might be distracting on compass. The rest can be delayed for next release. Do we need to hide engineer/covop build/destroy icons too, or should these be displayed at all time (like the revive icon for medics)?

**Comment by Aciz** [comment]
I was just talking about this with @Aranud over at discord, he said he will tie the compass icons to the cvar later today (and fix them being affected by picmip).

**Comment by rmarquis** [comment]
Distance unit of obj icons is set through the `cg_drawspeed` cvar, which is a bit odd, and especially annoying if you don't want to display speed but still desire to have distance unit.

I'd suggest to use a more global cvar (like `cg_drawUnit` ?) with 0/1/2 for "unit/metric/imperial", and simplify `cg_drawspeed` to 0/1/2 with "No/Yes/Yes + Max Speed" instead of the actual 6 values mess.

**Comment by rmarquis** [comment]
Note: the revive icons displayed through walls have a significant impact on gameplay, compared to those that don't use the feature. They are (rightly) deemed too overpowered for use in comp (cvar turned off in configs), but also are kinda unfair in public play too. 
These goes well beyond helping people that don't know the map well, and as such are quite different from static objectives.

I'd heavily suggest to not show them through EnvAwarness. Also, as another small advantage this would avoid having a doubled icon on the screen when the teammate to revive is in the field of vision, which is quite ugly.

**Comment by rmarquis** [comment]
Only static objectives are allowed now, so the `cg_drawEnvAwareness` cvar enforcement could be removed from comp config, if there is no further objection.
