### ISSUE TITLE
Adjust fov range check

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1175]
Author: @rmarquis (Spyhawk)
Date: 2019-01-18
Redmine Issue: 1175, https://dev.etlegacy.com/issues/1175

---

The field of view (fov) has been adjusted in Legacy so the default value is always "natural" by default, regardless of actual the resolution. This is done by using the "horizontal FOV formula":https://en.wikipedia.org/wiki/Field_of_view_in_video_games

There are still a few fov adjustment left to do in the code though. These value have been designed for the 4/3 screen era, and are not adequate when used with nowadays 16/9 screens.
The competition configs we ship have a range check from [90, 120]. The modern equivalent would be [73.74, 104.82]. Currently [90,120] on Legacy would be [106.26, 133.27] in other mods, so our values are"shifted" and need to be fixed.

A few notes:
* MGs and Tanks use a specific "zoomed" fov of 55 and 75, respectively, and are properly adjusted automatically too.
* Maximum fov value is forced to 160, while  the minimum fov is forced to 90. We might want to lower this value to allow for quick zoom when shooting?

In attachment a few screenshots for fov comparison between Legacy and other mods. Legacy fov 90 is the equivalent of other mod fov 106.

---

Related issue(s): #470

---

Related commit(s):
d25ad0c6efaa941a1f7c85b71f30171c4bc0eb4e - misc: adjusted cg_fov range check in configs, refs..

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-01-18T21:56:06Z

---

To be noted: some players use some "zoom" script to temporarily reduce the field of view but ease aiming on target (spread will still be the same).

Funnily enough, that wasn't possible in the 4/3 era, but when 16:9 screen came on market, suddenly the [90, 106] range was zoomed.
With Legacy forcing the minimum at 90, we're more or less back to the original design.

I'm not strictly against allowing a zoom here, just pointing it out - thought that was funny.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-01-18T23:35:42Z

---

Changed range check to [90, 105]. The upper bound is now the equivalent of 120 in other mods, while the lower bound stays at 90 preventing zoomed scripts (this is what binocs and covops are for).

**Comment by Aranud** [comment]
We should reconsider the currently set range [90 - 160] and adapt this to take into account the change to FOV calculations in legacy mod. 
After a lengthy discussion at Discord, we collectively decided to propose a new range of values to account for this change in the way FOV is calculated: [75 - 130]

As it was pointed out, vanilla values have been designed for the 4:3 screen era, and are not adequate when used with nowadays 16/9 screens.

If we are modernizing the game, we should allow modern fov, and looking at other FPS games, it's lower than 90.

> The default FOV value in BFV is 70, the minimum is 50, and the maximum is 105
> The minimum FO Vvalue in COD is 60, the default on PC is 80, and the maximum is 120.
> HL minimum 75, maximum 90.
> Borderland minimum 60, maximum 120, default 75
> etc etc

Yes, engine and view model are different from ET, but screen resolution are a lot differents from players to another.

The aim system and firing mechanics were made for good old 4:3 screen at the time. 
If we don't allow lower fovs anymore, we should decrease recoil and stuff to compensate because people cant aim as precise anymore, due to player models appearing smaller. 
Reworking it for 16:9 would need a lot effort and could alterate the gameplay. This solution couldn't be considered.

Also, there is cons and pros using different FOV. Lower the fov better the aim but less environment visible. With higher fov, the opposite gain are set. 
In fact, this remain balanced.

Binocular range are [4 - 20] and uses same values as vanilla for fov, meaning on 16:9 its zoomed out more compared to vanilla.

Finally, preventing zoomed scripts isn't really a big deal. We could let this responsability to the server owner if they really don't want this mechanics. 
But it would not really give a real advantage for players doing so, just a bit of conford.

**Comment by rmarquis** [comment]
Just as a general note, that might be relevant or not:

* Many modern games use lower FOV because they are available on console (distance of player to screen is bigger than on PC).
* There are also more and more ultrawide screens on market with 21:9 or even 32:9 ratio, in which case a higher upper bound might still be required
* Also: beware that some games measure vertical FOV rather than horizontal FOV, there isn't a single standard here (no idea about the above mentioned)

**Comment by Aciz** [comment]
> * Many modern games use lower FOV because they are available on console (distance of player to screen is bigger than on PC).

Yes, but most (if the developer cares at all) support adjusting the FOV higher on PC, yet the values as mentioned above are usually still lower. Keeping mind that ET is a lot more fast paced game than most FPS games, higher FOV is still desired than the average, but lowerbound of 90 is just too high, especially since there are pretty long range gunfights in most maps.

> * There are also more and more ultrawide screens on market with 21:9 or even 32:9 ratio, in which case a higher upper bound might still be required

I think you misunderstood this a bit, as you actually want LOWER value of FOV on ultrawides. Here's a demonstration:

Current 90 minimum @ 16:9
![2021-08-31-202800-supply](https://user-images.githubusercontent.com/14221121/131549334-864d186a-80cc-44af-a8bf-a4ba0632d0b8.png)

Current 90 minimum @ 21:9
![2021-08-31-202824-supply](https://user-images.githubusercontent.com/14221121/131549366-04bddf5c-cac1-4aed-aae8-5a353f5dc7df.png)

Current 90 minimum @ 32:9
![2021-08-31-202838-supply](https://user-images.githubusercontent.com/14221121/131549394-0a617f3f-c23d-4d76-9759-36f16489279a.png)

New proposed 75 minimum @ 16:9
![2021-08-31-202914-supply](https://user-images.githubusercontent.com/14221121/131549437-4f929cf7-978f-45a5-95c0-7541cde4171d.png)

New proposed 75 minimum @ 21:9
![2021-08-31-202932-supply](https://user-images.githubusercontent.com/14221121/131549461-0daa59dd-408d-4d6e-abde-cf8c199044f8.png)

New proposed 75 minimum @ 32:9
![2021-08-31-202950-supply](https://user-images.githubusercontent.com/14221121/131549478-fe9aaab7-98ff-4eeb-9eb1-c33555a387ea.png)


I don't think I need to explain why having upperbound 160 with ultrawides in mind isn't required, but for the sake of it, heres 160 fov with 32:9 :D 
![image](https://user-images.githubusercontent.com/14221121/131549910-aa9c541e-8d4f-42e7-b0e0-21fa50c0fe63.png)

**Comment by rmarquis** [comment]
> you actually want LOWER value of FOV on ultrawides

Yes, correct.

**Comment by Aranud** [comment]
> Also: beware that some games measure vertical FOV rather than horizontal FOV, there isn't a single standard here (no idea about the above mentioned)

FPS games since 2005 are for the majority HOR+ (horizontal plus) : 
> HOR+ is the most common scaling method for the majority of modern video games. In games with Hor+ scaling, the vertical FOV is fixed, while the horizontal FOV is expandable depending on the aspect ratio of the rendering resolution; a wider aspect ratio results in a larger FOV. Since the majority of screens used for gaming nowadays are widescreen, this scaling method is usually preferred as wider aspect ratios do not suffer from reduced FOV with it. This becomes especially important in more "exotic" setups like ultra-wide monitor or triple-monitor gaming.

ET is Vert- (vertical minus) : 
> Vert- is a scaling method used by some games that support a wide variety of resolutions. In Vert- games, as the aspect ratio widens, the vertical component of the field of view is reduced to compensate. This avoids distortion of objects in the game world but results in a smaller field of view on widescreen resolutions, and may become especially problematic with extremely wide resolutions, such as those common on multiple-display setups

Well, a quick win would be to allow a lower FOV for now. Until we got the correct formula to allow wider screen to display a correct resolution.

**Comment by rmarquis** [comment]
> ET is Vert- (vertical minus)

Hu, you sure about that? Because we indeed use the HFOV formula for automatic scaling.

**Comment by Aciz** [comment]
I guess he meant vanilla ET? That was vert-, legacy is indeed hor+.

**Comment by Aranud** [comment]
> I guess he meant vanilla ET? That was vert-, legacy is indeed hor+.

Yes, ET vanilla (not ETL). I should be more precise next time.

**Comment by rmarquis** [comment]
Oh right, thanks you both for the explanation!
