### ISSUE TITLE
Use OpenAL as default sound engine

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1213]
Author: @rmarquis (Spyhawk)
Date: 2019-03-01
Redmine Issue: 1213, https://dev.etlegacy.com/issues/1213

---

There is some delay between the weapon fired and the sound produced, compared to vanilla. This overhead is caused by SDL that is used for input and sound.
OpenAL has some minor issue (see #977), but noticeably reduces that delay. Changing the default sound engine from SDL to OpenAL should give players a better overall experience.

---

Related issue(s): #977

---

Related commit(s):
de95e07678ef982d538c57e20019f4ca130a7444 - client: use OpenAL as default sound backend, refs ..

**Comment by ETLegacyTeam** [comment]
From: @IR4T4 (IR4T4)
Date: 2019-03-01T14:56:53Z

---

As far as I know you have to install additional software to make it work?

We might extend the installer to do this (option to also install openAL and set cvar s_backend). Let the user decide.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-03-01T15:04:44Z

---

No, OpenAL is built-in already. There is nothing to add, it's there as an option in UI.
I actually prefers it to SDL (quality seems better, and it's a must for anyone that has more than a dual-speaker system).

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-03-09T17:22:53Z

---

Done. In case the code is compiled without OPENAL support, the client will fallback to SDL2 automatically.
Players that wants SDL2 as sound backend can change it in the settings (only the default is changed).

**Comment by BystryPL** [comment]
I suggest reverting this to SDL2 as default sound system, since OpenAl is too broken to be used (every player complains about it and has to switch to SDL2 anyway, for instance the evironment sounds are too loud - CP beeping from the other side of the map, etc.). Not everybody is aware that it's actually possible to switch to other sound system which is not broken or doesn't know how to do it. Hence my suggestion to revert it to a playable default sound system.

**Comment by rmarquis** [comment]
Done. I suggest interested devs keep using OpenAL so we eventually get a chance to fix related issues #977, #1262.
