### ISSUE TITLE
/class s 4 won't pick smg as secondary weapon

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1256]
Author: @rmarquis (Spyhawk)
Date: 2019-04-20
Redmine Issue: 1256, https://dev.etlegacy.com/issues/1256

---

In https://github.com/etlegacy/etlegacy/blob/922894084b9c87650bf12d46bc9d56e3a93817f8/src/cgame/cg_consolecmds.c#L1253, cgs.ccSelectedPrimaryWeapon isnt updated so /class s 4 (soldier with Panzerfaust/Bazooka) won't pick smg as secondary weapon.

**Comment by ETLegacyTeam** [comment]
From: @rmarquis (Spyhawk)
Date: 2019-04-25T18:12:44Z

---

This actually works already, but you have to pass secondary weapon as extra parameter: `/class s 4 2` (0=colt, 1=dual pistol, 2=smg)

**Comment by mittermichal** [comment]
if you are currently non-soldier class you will spawn with akimbos instead of SMG after `class s 4`

re-open or create new issue?

**Comment by Aciz** [comment]
Is this really an "issue" per se? I mean pistol/akimbos are the default secondary for soldier, even with soldier lvl 4. You're not defining secondary weapon, so it's just picking the default. Are you saying we should make SMG the default secondary?

**Comment by Aciz** [comment]
Nvm there is indeed a logic issue in the code.

https://github.com/etlegacy/etlegacy/blob/f25d658c05afe20b940d96f76079659c88e1b4b8/src/cgame/cg_consolecmds.c#L1314-L1349

The check at L1335-1338 is what causes this issue:
```cpp
// if player handling a similar weapon in primary slot, don't show it 
if (classInfo->classSecondaryWeapons[i].weapon == cgs.ccSelectedPrimaryWeapon) 
{ 
 	continue; 
} 
```

This will invalidate SMG as a potential secondary weapon for soldiers, because I guess `cgs.ccSelectedPrimaryWeapon` is not correctly updated as it's only set from limbo panel, and defaults to SMG as primary, which then blocks it being a secondary weapon. Opening the limbo menu once after using `class s 4` so it shows Panzerfaust/Bazooka as primary, closing the menu and issuing the command again will correctly set SMG as secondary weapon, because `cgs.ccSelectedPrimaryWeapon` is now set to Panzerfaust/Bazooka.
