### ISSUE TITLE
Successful vote cancelled when warmup ends

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1310]
Author: @rmarquis (Spyhawk)
Date: 2019-06-22
Redmine Issue: 1310, https://dev.etlegacy.com/issues/1310

---

When a vote is passed in warmup, it will be cancelled when the warmup ends if the vote timer isn't finished at that time even if it looks like the vote would have passed.
Check the set vote percentage limit, and approve the vote if it passed when warmup ends.
Alternatively, shorten the vote duration to warmup duration. This might be a much simpler/cleaner solution.

**Comment by timosmit** [comment]
I am questioning whether this really is a bug that we should fix. Note that there's also the `g_voting` bitflag cvar, for which bitflag 1 allows to pass the vote based on the actual voters, rather than the total amount of players. If it's desired to pass the vote early, server admins should enable bitflag 1.

**Comment by rmarquis** [comment]
I'd consider this more as an "annoyance", or side effect than a real bug. It's annoying because it does happen, and sometimes quite often depending on the g_warmup value on some pub servers.

I am however unsure of the proper way to avoid it. Maybe the cleaner way would be simply to prevent any vote when the warmup counter isn't big enough (with some message displayed on the caller screen).

**Comment by timosmit** [comment]
> I am however unsure of the proper way to avoid it. Maybe the cleaner way would be simply to prevent any vote when the warmup counter isn't big enough (with some message displayed on the caller screen).

This I would prefer. Using the vote time as a minimum could probably disable voting during warmup on most public servers, since they usually have a warmup shorter than 30 seconds. I would not really call that bad, though. Fixing the annoyance of an ignored vote or being unable to participate in the vote (due to late-joining) seems more valuable to me.

**Comment by timosmit** [comment]
This should be fixed with changeset dc4828e.

**Comment by Aranud** [comment]
I was wondering if we can match the remaning warmup time with the vote time left as other solution

**Comment by Aranud** [comment]
We should try to match the remaning warmup time with the vote time left as other solution
