### ISSUE TITLE
Create an 'official', Automated Build image on Docker Hub

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1357]
Author: pataquets (pataquets)
Date: 2019-10-31
Redmine Issue: 1357, https://dev.etlegacy.com/issues/1357

---

Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches.
Also, documentation could easily include a canonical "docker run" statement to quickly spin up a ET:L server with just a single command.
Also, by taking advantage of layered Docker images, a "base" (server-only) image can be built and a child image for running on desktop, if more packages/libs are needed. There are some images around on Docker Hub, but having an authoritative, built from source base image would help contributors and avoid duplicate efforts. Thus, the whole community can focus on maintaining a common image, but allow also individual contributors to base theirs in the official one. The base image should be as unopionionated as possible, though. Initially just a "compiled binaries" would do, and iterating from there, if needed. 

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags and branches.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by rmarquis** [comment]
Closing. So far, we don't plan to officially support anything other than the static binaries, and as such third party build is just extra work. Anyone interested might do it though.

**Comment by pataquets** [comment]
Fair enough, @rmarquis. Thanks for the feedback. I have two main doubts.

I wonder, if anyone interested finally manages to assemble a Dockerfile which creates a 'canonical' (ie. `easybuild.sh` based) build, would such a Dockerfile be accepted as a PR? It might even contain a comment clearly stating it's a non-supported method (although I think that, just invoking `easybuild.sh` would not be too prone to breaking, since it's quite smart and self contained). 

Also, added to the above, linking a Docker Automated Build would add some sort of CI-like build, that would help catch some build errors, but this is not required and could also be clearly stated as a "non-official, unsupported, use at your own risk" build. But I'm not 100% on it, since it's understandable wanting to avoid the added burden, thou.

**Comment by rmarquis** [comment]
I have personally zero interest in a docker file, due to the extra maintenance and inevitable user support that will take away time and effort on the long run.

If anyone wants to add the above on their todo, feel free to do so. I'm just not that person.
