### ISSUE TITLE
Hide 32 bit servers on 64bit clients

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#1375]
Author: @rmarquis (Spyhawk)
Date: 2019-12-22
Redmine Issue: 1375, https://dev.etlegacy.com/issues/1375

---

Using the g_oss serverinfo cvar, filter out 32 bit servers that can't be connected to with 64 bit clients (linux, macosx).
Find a way to enable this at compile time?

Third party mods released in 64bit (etjump) are expected to implement this cvar.

TODO:
* remove the extra architectures we'll never support (pandora, ...) from g_oss.

---

Related commit(s):
0219887a26211cd43172cfd8eb9541e235c071f8 - game: cleaned up g_oss bitflags, refs 1375

**Comment by LiamDawe** [comment]
This would be really amazing to see finally added in, as today with the new release every server I tried so far will not let me in. I assume because I downloaded the 64bit client. It's a really bad intro to the game for any new player, if there's no real indication on why so entirely filtering them out is a must have.

**Comment by jackeri** [comment]
This was finally implemented using a build time manifest that gets generated by the build pipeline. The commit in question is: d2a42b4675b18419b855dacb070610bea546cf91
