### ISSUE TITLE
Allied hand model removes silencer from Axis silenced Luger in 1st person

### ISSUE THREAD

**Issue by realkemon** [etlegacy/etlegacy#1430]
That's a horrible title, but I suppose rather descriptive.
So, when you spawn as an Axis cvops and equip your silenced Luger, remove the silencer. You will see that the hand model appears to be an allied arm. At least the skin is brownish, which is definitely closer to an Allied uniform than the Axis cvops skin.

**Comment by realkemon** [comment]
![shot0002](https://user-images.githubusercontent.com/8881420/79484082-72fae280-8013-11ea-9d3a-f96afbf8c108.png)

**Comment by realkemon** [comment]
Apparently, this is not exclusively happening for the silenced Luger.
Mauser from Discord reported the same thing happening for Axis that pick up Allied weapons. See attached screenshots. 
![2020-04-16-201655-fueldump](https://user-images.githubusercontent.com/8881420/79493757-3c789400-8022-11ea-867a-b3e71e03de8a.png)
![2020-04-16-201702-fueldump](https://user-images.githubusercontent.com/8881420/79493773-40a4b180-8022-11ea-9feb-cbe52c7f6570.png)

**Comment by Aranud** [comment]
Rifles and singles pistol are affected because there are no allies/axis .skin files linked to theses weapons. If you look at Thompson/MP40 or MG42/Browing, they all provided .skin files which indicate the models to reused following the team (see .weap files) . 

We have to create all the necessary .skin files to apply the correct models.
