### ISSUE TITLE
Provide snapshot builds for public testing

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1451]
At the moment we ship a semi-private snapshot build to a single populated server. While this has undoubtedly helped in having continuous feedback and testing, the process hasn't always been as smooth as it could have been (for various technical and non technical reasons).

The mod has also reached a point where it is (mostly) stable with few known regressions, and it is time to let others experience that as well.

Provide testing snapshot builds publicly on our website, in order to:
* get more debugging information to work with for issues currently open
* extend the playerbase coverage
* get a good input from the serveradmins (in theory at least)
* speed up the next official release, rather than stalling the release process indefinitely (as we are currently experiencing)
* not waiting for input when new features or fixes do not reach a large audience, as this may also be discouraging to us, the contributors.

Side consequences of having regular testing builds include:
* giving incentive for new contributors, as code will hit live servers rather sooner than later.
* may encourage coders to fix bugs themselves
* bring Legacy to the attention of possible new players or even contributors.

Downside might include:
* lower quality of feedback from casual players,
* not easy access to logs in case the issues is more troublesome to debug

To be noted:
* we have an "autoupdate" feature built in (client and server side), but disabled by default - and that has not been tested for years.
* we only make use of the "update checker" on the client side, which is basically an update notification build in the client (with the help of some version number sent from our server infrastructure). It works for stable builds, but it could be expanded to test builds, as a sort sort of "beta" channel.
* having the same kind of notification for servers running these snapshot builds would be ideal, as to avoid the spread of unstable code that would never been updated by their admins. An update notification that would be sent from the "obsolete" server to the cgame module and displayed in a corner as a watermark, for example.
* we should consider the possibility to bring back autoupdate for test builds, though many admins might have (valid) concerns.

**As such, it is suggested to:**
* adjust the notification code for these snapshot builds (client & server side). This requires some minor work on our web infrastructure.
* adjust the browser UI to display running build version (Legacy mod only) (see #1420)
* make public testbuilds (can be delayed to to ensure it first works on official server)
* warn people about the stability of these builds
* gather fresh feedback related to current builds to fix it in time
* care less about final release, can in fact do LKG stable releases instead

We've been talking about "releasing early, often" so many times. It's probably time to actually do it.

(ticket adapted from a suggestion from @timosmit)

**Comment by Exagone313** [comment]
Providing snapshots for client and server + mod are two different tasks.

For client:
* Most of user base just want the client.
* As most of active servers aren't using legacy mod, client needs to be tested against other mods too, in case of a regression on that part.
* It needs to be clearly emphasized that such snapshot rebuilds are **not** for beginners as things **will** break some day. As such, it should be installed separately instead of replacing release version.
* It could be more stable to make a separated program which updates the game, so that it can be called either by the game or separately. A separated updater can still run if client doesn't. A separated updater could support downgrades (for bisecting) in a more natural manner than within the client itself.

For server:
* Server owners will probably not want auto-update which means random downtime.
* I think it would be easier to provide a script which simply downloads latest snapshot (or a specific snapshot version) on specified paths. Then server owners can create cronjobs if they want to.
* You could make a Docker image, but such setup requires to make choices that are different from actual server deployments, e.g. for mod downloading. (Note: with Docker you can have an image with installs a Linux 64-bit server that works for all different client platforms, which could improve the overall compatibility.)

**Comment by rmarquis** [comment]
> Providing snapshots for client and server + mod are two different tasks.

Yes, and no. Our build infrastructure pretty much tie together the mod/engine part, and this isn't really an issue for snapshot distribution. There is no advantage of separating them (users will only use the client, server owners the server + mod).

> As most of active servers aren't using legacy mod, client needs to be tested against other mods too, in case of a regression on that part.

Yes. Such work as been done as part of #1161. It's not perfect as some servers still crash with ETL client, but I suspect this is due to AC (f.e. some silent servers work, some don't, on the same mod version).

> It could be more stable to make a separated program which updates the game

The built-in updater is essentially a [separate project](https://github.com/etlegacy/Update-Installer). It used to work fine, but it hasn't been tested on a wide scale.

> Server owners will probably not want auto-update which means random downtime.

I agree. However, we still need to **strongly incite** admins to update regularly. See above for possible solutions.

A dockerized solution sounds nice, but it can't be used on many (if most?) game hosting service afaik. That is outside my personal expertise, or of the existing team afaik. Someone would need to fill the gap. On the other hand, the existing solution is ready to be deployed.

**Comment by timosmit** [comment]
> A dockerized solution sounds nice, but it can't be used on many (if most?) game hosting service afaik. That is outside my personal expertise, or of the existing team afaik. Someone would need to fill the gap. On the other hand, the existing solution is ready to be deployed.

I am not familiar with any game hosters that use Docker for the game server orchestration; a quick glance at Google does not yield any results either. That should not be that surprising, since some of the benefits of containerization are negligible in the context of a game server. Ideally, W:ET game servers are servicing players 24/7, hence they cannot easily be killed, restarted or moved to different nodes without an impact on the player experience (as they're stateful).

Of course it would greatly reduce the effort of spinning up a server, but I suppose most hosting companies have had a solution for this already. Nevertheless, providing a Docker image is definitely helpful.

**Comment by Exagone313** [comment]
For the record, I have made a Docker image which builds from source and then run a server [here](https://gitlab.com/Exagone313/docker-etbloat), I can adapt it for just downloading legacy server and mod from a server (I can't build for macOS). I can also "rebrand" it for etlegacy since it works with it too (with some parameters adjusted).

**Comment by rmarquis** [comment]
> care less about final release, can in fact do LKG stable releases instead
>
> We've been talking about "releasing early, often" so many times. It's probably time to actually do it.

Some extra thoughts here: one pitfall of a "last known good" stable release might be to get stuck in some "rolling release" trap: each new version has fixes, but introduces some new bugs as well, with the overall quality not improving anymore.

We can only improve quality by having tighter scope, and by reducing the number of major changes introduced in the codebase. Having a targeted "real" release helps to achieve that goal.

**Comment by zedar187** [comment]
A tighter scope sounds good. If a certain set of features is defined beforehand, a stable release can be finished in a more focused way. The snapshots are, as they should be, just for catching bugs. As soon as the snapshots run satisfying stable, a final build + installers will be created. 

This would prevent the whole "oh, this feature might be handy, we _need_ to implement it before the release" situation, until the todo list is exploding.

**Comment by timosmit** [comment]
Exactly. I'd opt to use the GitHub milestones (and projects, optionally) more actively. Over the last week I've tried to do some prioritization for the 2.77 milestone (you can drag issues) to gain an overview of what needs to be done to get a release out.

Possibly we can tighten the scope for 2.77 based on this?

**Comment by rmarquis** [comment]
With the pak isolation system now working, new downloads of the mod will be put in `homepath/legacy/dlcache`. The default loaded UI will be the UI located in `basename/legacy`, as shipped by the snapshot build.

However, we still have the issue that players/testers will have old download mods in `homepath/legacy`, preventing the default UI (basepath) from being loaded _unless_ they clean their `homepath/legacy` folder first.

To avoid many stupid issues, I'd suggest to implement #1396 first, which will force the creation of a new empty, clean folder (note: ideally, don't ship any new build to TM once this is done and until the isolation-enabled client is ready to be shipped with snapshot builds).

**Comment by rmarquis** [comment]
> However, we still have the issue that players/testers will have old download mods in homepath/legacy, preventing the default UI (basepath) from being loaded unless they clean their homepath/legacy folder first.
>
> To avoid many stupid issues, I'd suggest to implement #1396 first, which will force the creation of a new empty, clean folder (note: ideally, don't ship any new build to TM once this is done and until the isolation-enabled client is ready to be shipped with snapshot builds).

Forget about the above, renaming can wait. There are more issues (f.e. adjusting path on our own infra) and that isn't worth it fixing before snapshot releases. Instead, ensure to put a *big red* communist *warning flag* on the snapshot download page, as well as on the official announcement post. Those that can't read shouldn't download snapshot test releases anyway.
