### ISSUE TITLE
Revive icon visible when spectating a non-medic

### ISSUE THREAD

**Issue by timosmit** [etlegacy/etlegacy#1465]
The revive icon is drawn when spectating anyone who's not a medic, e.g. a soldier, when you yourself are a medic. As the soldier is not able to revive anyone, it is kind of awkward to see the revive icon in this case.

**Comment by rmarquis** [comment]
I'm not sure to understand. Do you mean spectating not as spectator, but when following non-medic players when in limbo (as a medic)?

**Comment by realkemon** [comment]
Exactly. That was on my stream earlier. I was playing a medic and died to the respawn queue so I was following one of my teammates who was running around a downed teammate and I was getting frustrated (internally of course) that the player I was following wasn't reviving our downed teammate with the huge revive icon. I only noticed after a couple of seconds that my frustration was uncalled for because the teammate I followed was a soldier and didn't see that icon themself. There is little point in showing that icon in that case I think as nobody can do anything with that information. Neither the teammate who wasn't a medic nor I because i was dead.
