### ISSUE TITLE
Object marker shines through Covert smoke

### ISSUE THREAD

**Issue by zedar187** [etlegacy/etlegacy#1474]
You can see object marker on the enemies carrier through the smoke, making it easy to focus all the shooting to this very position. This gives the defending team an advantage.

![obj](https://user-images.githubusercontent.com/5468685/82132125-b72cfe80-97dc-11ea-83dc-f6271a226a90.jpg)

**Comment by ryzyk-krzysiek** [comment]
The same could be said about the revive marker, which can also have its advantages but on attacking team more I guess.

![Revive marker](https://user-images.githubusercontent.com/4499367/82558243-88f94700-9b6d-11ea-90c5-2af63388220e.png)

**Comment by Aranud** [comment]
Sprite are drawn over the fog by design in renderer : https://github.com/etlegacy/etlegacy/blob/bacade7892a1a2c1563c6897897e2854e17b6a6e/src/renderer/tr_main.c#L1667-L1683

The renderer try to figure if the sprite is inside a fog and sort the draw order : https://github.com/etlegacy/etlegacy/blob/bacade7892a1a2c1563c6897897e2854e17b6a6e/src/renderer/tr_main.c#L1538-L1541
