### ISSUE TITLE
Object marker reveals position of hiding player

### ISSUE THREAD

**Issue by zedar187** [etlegacy/etlegacy#1477]
As the marker sits on top of the model, it reveals the position when hiding. Thus the attacking team has a tactical disadvantage.

I'm not sure if the marker should be visible to the enemy in first place. IMO the marker is only needed for teammates. The general icon, that the object is on the way, should be sufficient for the defending team.

![obj2](https://user-images.githubusercontent.com/5468685/82132472-6a4b2700-97e0-11ea-948c-b84a29ee6b8c.jpg)

**Comment by realkemon** [comment]
#1474 Related to this, but not duplicate. Icon visible through smoke can be considered a bug, obj icon visible above head behind cover is a highly questionable gameplay mechanic. Its removal/different implementation would be a gameplay change, but imo a good one.
One suggestion I would like to make is to combine it with #1125 this ticket to give every player a slight glow. Allies = blue, Axis = red, obj carrier = green.

**Comment by rmarquis** [comment]
Is the issue reported that the icon might reveal the player position behind cover, or that the icon should not be visible at all? Because if it is really the latter, I am not sure how anyone in the enemy team would be supposed to know which player to kill in priority.

If it is the former, I suppose we can use a similar line-of-sight mechanic from the covops, and only display the icon if the player is seen.

**Comment by ryzyk-krzysiek** [comment]
Objects such as window block the objective icon from appearing above players head.
![Bez tytułu](https://user-images.githubusercontent.com/4499367/138846060-90f4df0d-a0f2-45a1-8500-704c470d04e6.png)

**Comment by Aranud** [comment]
See #644 and #646 mainly with related explanation https://github.com/etlegacy/etlegacy/issues/644#issuecomment-595407985
