### ISSUE TITLE
MG42 crosshair discrepancy when in shooting mode.

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1479]
Players crosshair when in shooting mode of MG42 is not matched with the real crosshair placement. 

![1](https://user-images.githubusercontent.com/4499367/82319440-dc369280-99d1-11ea-9aa5-9c4cc4a4c634.png)
Cannot shoot around the corner even though the gun barrel and crosshair seem to be in correct position.

![3](https://user-images.githubusercontent.com/4499367/82319473-ea84ae80-99d1-11ea-82ea-b7930c602cd5.png)
The same situation as previously but after leaving shooting mode you actually see that player was aiming at the wall.

![2](https://user-images.githubusercontent.com/4499367/82321595-5f0d1c80-99d5-11ea-92d0-721ead80d6dd.png)
The further you go to the edge of cone of fire the bigger the discrepancy gets, I believe the offset is present only on the x axis.

**Comment by rmarquis** [comment]
Related: #1368.

**Comment by rmarquis** [comment]
This looks like a vanilla issue. I can reproduce on etpub, jaymod and etpro. The issue seems independent from client fov (tested with both fov 90 and 106.27 on vanilla ET).

Note: tracers seems to start from way above the proning player, when aiming up, as vertical axis seem affected too.

**Comment by rmarquis** [comment]
This happens because the starting point of bullets is actually set at the viewpoint (the eyes, .. not the weapon!). However, in prone position the viewpoint isn't brought forward, but kept on the middle of the back. This is usually not an issue, as this starting point is always in line with the prone body.

In this case with a settable weapon, a rotation point is fixed and the starting point won't be in line with body anymore when some rotation is applied, making it apparent bullets are shot from behind the viewpoint. See `g_debugBullets 1`.

Simply moving forward this starting point in `Bullet_Fire_Extended()` when prone and when using settable weapons (or for all weapon) should be enough to fix this issue.

**Comment by Aranud** [comment]
We could either remove this part of code https://github.com/etlegacy/etlegacy/blob/6a9754e176ce776d48a418a0c816698cc10df1f4/src/cgame/cg_view.c#L593-L605 
or duplicate it in muzzle trace computation to make it work https://github.com/etlegacy/etlegacy/blob/5de0a0e06d1be18e3cc7d61fbb38751e0b7f3595/src/game/g_weapon.c#L3992

The questions are : What is the purpose of this code ? Why it create a small angle offset in view perspective ?
