### ISSUE TITLE
fireteam icon of disguised enemy reveals him if he has uniform of mine

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1503]
![shot0001](https://user-images.githubusercontent.com/4035800/88324680-54983780-cd24-11ea-8892-d78dd04c8d30.png)
If I am alone in fireteam and I see fireteam icon, I know for sure its enemy with my uniform. The icon is even visible through walls.
This is easily fixed by not showng the icon if client_number != disguiseClientNum. 
But then if I have my whole team in fireteam then I would know its enemy if I don't see the icon. In that case the icon should be drawn.

**Comment by rmarquis** [comment]
Good catch. Do note this issue has always been there, but in previous build selecting FT teammates was necessary to display the icon. Now the FT icon is always displayed - with a different colour when the FT member is selected.
I suppose a check to see if more than one player in the FT should be enough to cover this corner case.

I am not sure why the icon is displayed through a wall, but I suppose it is because the partially covered player is considered visible here.

**Comment by mittermichal** [comment]
It seems its visible when client has the player entity (is somewhat close, BSP tree thing, dunno how to call it).
> I suppose a check to see if more than one player in the FT should be enough to cover this corner case.

I think that would be fine if the icon was not visible through walls.

**Comment by rmarquis** [comment]
Yes, probably that. That code uses the very same code of in-game vchat icons ("I need health/ammo" icons), so I guess the issue is also present there, but we might be able to reuse the coverops traces to ensure players are actually visible to players.

**Comment by rmarquis** [comment]
I am unable to reproduce the icon visible through wall. It works as expected on my side:
![2020-07-25-143600-supplydepot2](https://user-images.githubusercontent.com/162442/88457130-42cda600-ce84-11ea-942c-0f354d9c37d1.png)

**Comment by mittermichal** [comment]
my bad, had to remove old legacy pk3s and dlls from homepath. Then it was same as yours.

**Comment by rmarquis** [comment]
> But then if I have my whole team in fireteam then I would know its enemy if I don't see the icon. In that case the icon should be drawn.

That case is not fixed. This might be the more important aspect to fix (?), so the added complexity might be worth here.

**Comment by Aranud** [comment]
With the current change, you don't see the icon if the enemy steal your own uniform. 
Your allies could, so there is more chance than your allies will spot the enemy than you.

If there is 2-3 players in FT, it would be easy to spot the enemy if the icon are show.
In the case of 4-6, I agree it would be harder.

Anyway, since the allie would see more icon than you, let change the logic to check the number of FT members instead of client uniform. Every player must have the same chance to spot the enemy.
