### ISSUE TITLE
Stealing uniform / defusing dynamite / planting dynamite gets randomly interrupted

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1553]
Doing one of the above-mentioned activities gets randomly interrupted. The blue progress bar disappears and one has to move / change position to resume the task.

**Comment by BystryPL** [comment]
https://streamable.com/lkvg26

**Comment by jackeri** [comment]
Reportedly this does not occur anymore.

**Comment by jackeri** [comment]
Woops wrong issue.

**Comment by ryzyk-krzysiek** [comment]
The last problem should be fixed in this commit https://github.com/etlegacy/etlegacy/commit/20d49b2e5c5785306d7184efa5b6c06f4d718dbe . 

The issue was that when trace was starting in solid (dynamite/player hitbox) it wasn't returning correct entity number and so the trace result was that it hit nothing.

It's now possible to lay directly on top of enemy player and steal his uniform, but note that teammate players bodies can still block it.
