### ISSUE TITLE
Picking up (switching current weapon) weapons from ground is hindered or impossible

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1554]
Usually that can happen if the weapon lies close to another object (I think), but it needs to be confirmed.

**Comment by ryzyk-krzysiek** [comment]
Example: https://www.youtube.com/watch?v=41U7wG4s-1Q

Demo: [2021-02-06-200637-adlernest Cant swap weapon 0510.zip](https://github.com/etlegacy/etlegacy/files/5937558/2021-02-06-200637-adlernest.Cant.swap.weapon.0510.zip)

**Comment by Aranud** [comment]
Vanilla behaviour.

The corpse hide the weapon ... and the trace hit the corpse first because it's heigher than the weapon.

The logic behind it : we don't ignore corpse to check either or not a covert ops could steal the uniform. And the check don't bother to look at the player class. Same thing once the uniform stealed.

For a correction, we have to adjust these parts of code :

* For ent detection https://github.com/etlegacy/etlegacy/blob/8ac48ee0fe2791628e2763239263f80a2ab3c3c9/src/game/g_cmds.c#L4103-L4127

* For hint detection  https://github.com/etlegacy/etlegacy/blob/8ac48ee0fe2791628e2763239263f80a2ab3c3c9/src/game/g_main.c#L1038-L1041
* https://github.com/etlegacy/etlegacy/blob/8ac48ee0fe2791628e2763239263f80a2ab3c3c9/src/game/g_main.c#L1073-L1095
