### ISSUE TITLE
[Linux] Wayland support

### ISSUE THREAD

**Issue by A6GibKm** [etlegacy/etlegacy#1607]
According to https://github.com/etlegacy/etlegacy/issues/891 builds should automatically have Wayland support. At the moment 2.77 runs on x11 only. 

According to the logs:
```
       0 SDL build version 2.0.14 - link version 2.0.14
       0 SDL initialized driver "x11"
       0 Initializing OpenGL display
       0 Estimated display aspect: 1.778
       0 ...setting mode -2: 1920x1080
```

This issue appears at least on the Linux 32bit build.

**Comment by rafal1137** [comment]
Its is a changelog of SDL itself. We have wayland disabled with current one.

https://github.com/etlegacy/etlegacy-libs/blob/8cc613f641a8bea65c2d0182012913315d42ad40/CMakeLists.txt#L674

**Comment by A6GibKm** [comment]
Thanks for the clarification, is there any reason it is disabled? To be honest I don't know if this would require a mayor effort or if it just amounts to having testers.

**Comment by rmarquis** [comment]
Afair, wayland has been disabled because it causes issue when compiling on some systems that fail due to wayland detection being faulty or something along the line of compiling with wayland support but not having it on the target system. It's pretty much uneven across the various Linux distrib, and pinpointing where exactly goes wrong and on which distro wasn't deemed worth it since X11 is here to stay.

You're welcome to do testing on your own, but I feel it might be easier for you to simply compile your own client with wayland support.

**Comment by jackeri** [comment]
I will fix the build machines support for wayland today'ish and enable it on the build.

**Comment by jackeri** [comment]
Could you test & confirm that the latest snapshot is wayland compatible: https://www.etlegacy.com/workflow-files

**Comment by Aciz** [comment]
Wayland works for me on the 2.77-42 build, but fullscreen doesn't work as discussed in #1592 (same issue on xorg and wayland)

**Comment by dragstor** [comment]
> Wayland works for me on the 2.77-42 build, but fullscreen doesn't work as discussed in #1592 (same issue on xorg and wayland)

Confirming this. Windowed and/or windowed-fullscreen works, but not the actual full screen.
[Patch coming soon.](https://github.com/etlegacy/etlegacy/issues/1592#issuecomment-792376337)
