### ISSUE TITLE
PAK isolation is broken

### ISSUE THREAD

**Issue by Aciz** [etlegacy/etlegacy#1609]
Test setup:
* Client: ETLegacy 2.77 Win x86 (Win 10 Pro x64 20H2, 19042.804)
* Server: ETLegacy 2.77 Linux x86 (Ubuntu 20.04.2 LTS)

PAK isolation at least with this setup results in an infinite download loop. When download starts, pk3 temp file is created in `fs_homepatch/etmain` folder, and once finished, pk3 appears in `fs_homepath/etmain/dlcache`. However, the download just restarts after that, and a new temp file is created. Only way to connect to a server running a custom map is to manually place the required pk3 into `fs_homepath/etmain` folder.

This is only an issue with custom etmain content. Downloading mods works, although every mod I tested triggered the download of the mod binaries twice before letting me connect.

While this should not be a mod-specific thing, for the sake of it, I tested the following mods:
* Legacy 2.77
* ETJump 2.4.0
* Silent 0.9.0
* ETPub 0.9.1 (with etpubc-20100628)
* Jaymod 2.2.0

I also tested running 64-bit versions of Legacy and ETJump on a 64-bit server, but the results were the same.

**Comment by Aciz** [comment]
Further testing: this does not happen on all servers. TeamMuppet ETLegacy/ETLegacy 2 work fine (37.187.79.49:27964 & 46.4.80.110:27990) but TeamMuppet ETJump (46.4.80.110:27966) does not work. First 2 servers are running ETLegacy server, while ETJump server is running on 2.60b. My own server, as tested initially, only causes the issue when the server is running on ETLegacy, 2.60b server works fine there. All servers utilize http downloads.

**Comment by rmarquis** [comment]
Implementing pak isolation for all third party mods revealed to be way too much of a hassle, so it eventually only was done for Legacy mod (see #1161). There might be a use case we missed.

Reading the above, it seems there is a lot going on, but could you try to pinpoint the issue more precisely?
Pak isolation is afaik strictly on the client side, so server running ETLegacy (etlded) or ET 2.60/b (etded) shouldn't make any difference here.

Is the issue only appearing when
* 1/ connecting to a server running a third party mod (not Legacy mod)?
* 2a/ the loaded mod on the client side prior to connection is Legacy (Legacy UI is visible)?
* 2b/ the loaded mod on the client side prior to connection is a third party mod (using `+fs_game <mod>`)?
* a combination of the above?

**Comment by Aciz** [comment]
1. No, the issue appeared in the test server running legacy mod
2a. Every other mod except ETJump was tested with legacy mod loaded upon client start, so this was the case with legacy mod
2b. ETJump was tested with `+set fs_game etjump` startup option, so ETJump was loaded before connecting

I will try to pinpoint a more exact condition when this happens definitely. I haven't looked at the code yet to see if there's any hints there. Should have more time to debug this later this week.

**Comment by jackeri** [comment]
This issue is caused by the download on the Muppets server being offline, meaning that the client disconnects, downloads a file and reconnects. This causes the dlcache flags to flipflop out of wack. On etjump servers where the download is not offline (like in the 99 jump server for example) the process works correctly.

**Comment by jackeri** [comment]
Correction the muppets server is not pure, which causes the dlcache to be disabled completely..

**Comment by Aciz** [comment]
For reference as to what we already discussed: my server is running with `sv_pure 1` and `sv_wwwDlDisconnected 0`, so neither of these issues should affect my server.

**Comment by isRyven** [comment]
Basically etmain is always containerized, despite the `fs_game` is being used, there is really no conditions when it would not containerize the content, however, there is a condition in vfs which sets the rule when it mounts the `dlcache`. I personally can't even connect to TM's etjump server, simply because disconnected downloading seems to be sort of "broken" on 64bit linux, as the main disconnected download logic is also kinda done weird in the first place (at least from the brief look), but it's out of scope of this subject. If you have a server list (w/ `sv_wwwDlDisconnected 0`) where the issue is reproducible, i would be glad to test them, so far the other servers i attended seems to be working fine (as the implementation logic is also quite simple really).

**Comment by Aciz** [comment]
We sort of figured this out: I had "too many" maps on my server, too many in this case being caused by incorrect comparison of basepath/homepath on server side, resulting in everything registering twice (at least to my understanding), and server not running in pure mode = pak isolation fails because it requires pure server to work, see 14c15ee346a8c8eede9e2f563b67d97c346552d6

But yes, it seems theres an issue with `sv_DlDisconnected 1` still.

**Comment by isRyven** [comment]
Nice catch. I had an impression that this header is a bit too loud and the actual reason lies somewhere else, and well, `sv_DlDisconnected 1` works by itself, at least i can connect and properly download stuff from the random NQ server `178.63.72.133:27960` that has it set. Non pure server connection is broken though, i guess the fix would be to check that there is an active connection upon `dlcache` mount, instead of pureness check, but it's also a bit tricky to do, as the check should be done in the `files.c` which doesn't really care about connection state (nor it really should). Probably some external function with the proper client connection state check could be defined to replace the ambiguous `fs_numServerPaks` check in the `FS_AddBothGameDirectories`.

**Comment by Aciz** [comment]
So the issue seems to be resolved now indeed, with a new snapshot build that contains the FS fix. And yeah you're right, `sv_wwwDlDisconnected 1` downloading seems fine, at least on my tests (tested both 32/64-bit Linux server with `sv_wwwDlDisconnected 1/0`, client was 32-bit 2.77 win-x86). The remaining issue is now pak checksum issue with non-pure servers.

**Comment by Aciz** [comment]
Final issue fixed in 5a6f28863217c04b2cb0350fa5250791b12a1ea0, closing this now.
