### ISSUE TITLE
Add Headshot for body on ground

### ISSUE THREAD

**Issue by PanzerMad** [etlegacy/etlegacy#1618]
i am just wondering if it was a missed part or not.

**Comment by Aciz** [comment]
As already explained in Discord, headshotting wounded player was never a thing in vanilla ET nor ETPro. Being able to headshot wounded enemies would greatly reduce the chance of being even able to get revived, since when you kill a player, they start the death animation and are stuck in position, and it's very easy to get a headshot or two while this animation plays, making gibbing players before they even hit the ground a common thing.
