### ISSUE TITLE
Custom Skins not working

### ISSUE THREAD

**Issue by estorado** [etlegacy/etlegacy#1647]
In the latest version of et legacy 2.77.1 custom skins are not working anymore. 
Attached you will find examples which where working with 2.76 and stop working with 2.77.1
There was already a discussion on Discord, but we didnt found the error.

I would really appreciate it if the functionality could be back in the next releases of etl.

[etr_sturmtruppe_v2.zip](https://github.com/etlegacy/etlegacy/files/6498810/etr_sturmtruppe_v2.zip)
[etr_us-rangers-2_v1.zip](https://github.com/etlegacy/etlegacy/files/6498812/etr_us-rangers-2_v1.zip)

**Comment by Aranud** [comment]
~~Related issue https://github.com/etlegacy/etlegacy/issues/393~~

**Comment by Aranud** [comment]
Short story : Put the custom pack in legacy folder instead of etmain.

Long story : The explanation behind it is legacy mod is overwriting the pak in etmain folder by his own asset. This mean the custom was alway overwrite by the skin containied in the pak3 from legacy mod folder. If you move your custom pack in legacy folder, it will change the load order. It was working in 2.76 because the skin and char files weren't in the pak3 yet. I did myself the change during the 2.77 : https://github.com/etlegacy/etlegacy/commit/fb89d3735e86c417f0c47c12bdc882642bb8bfb2 https://github.com/etlegacy/etlegacy/commit/02eb492c792bcde03201bd3b95c29caa23da74d5
