### ISSUE TITLE
`in_mouse 1` raw input doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by mittermichal** [etlegacy/etlegacy#1673]
Not sure if it supposed to work like that, but it is mentioned at: https://github.com/etlegacy/etlegacy/blob/7308381d00d9ed80d339435d04b199225ccff66a/src/sdl/sdl_input.c#L1516-L1530
I don't have "Raw mouse input failed" in console log.

I have to run `xinput --set-prop "Kingsis Peripherals ZOWIE Gaming mouse" "libinput Accel Speed" 0.0` each login
to be able to play without acceleration.

**Comment by rmarquis** [comment]
Afaik, acceleration and raw input are different settings - you just happen to have acceleration on with raw input.

**Comment by mittermichal** [comment]
when I play Q3 (cnq3 engine) I have raw input without any acceleration. System sensitivity or other mouse settings have no effect on Q3 mouse input. So it behaves different than ET:L. So I suppose that's not the way it should work. Or am I missing something?

**Comment by ensiform** [comment]
I would suggest you consider that there's always going to be some difference. Cnq3 probably doesn't use SDL at all? I know it doesn't on Windows.

**Comment by rmarquis** [comment]
The cnq3 engine source repo can be found here: https://bitbucket.org/CPMADevs/cnq3/src/master/

It's apparently using SDL2 too (on Linux), so maybe they're explicitly disabling mouse acceleration somehow?

**Comment by mittermichal** [comment]
tagging @mightycow :cow2:

**Comment by ensiform** [comment]
I'm kinda curious if [ETe](https://www.github.com/ETFdevs/ete) suffers same issue for you with SDL backend enabled.

**Comment by mittermichal** [comment]
@ensiform just tested ETe latest release and it works same as with CNQ3 with in_mouse 1. In-game mouse speed stays same regardles of OS setting.

**Comment by mittermichal** [comment]
@ensiform 
> with SDL backend enabled

or do I need to explicitly do something to enable SDL?

**Comment by mightycow** [comment]
I wrote the new base of the Linux code for CNQ3 almost 4 years ago now. I honestly don't remember much of what I've tried but I do clearly remember it was annoying to get mouse input working right for both native and virtualized systems with (mostly) the same code. I don't remember ever testing (or even thinking about) acceleration though, thinking that SDL2 would pick xinput2's raw input whenever possible anyway. Since no player ever complained about unwanted acceleration, the topic never came up.

I can see from a quick glance that CNQ3 and ET:L use the library differently, but I don't know why ET:L's approach would force a non-raw code path in SDL2 for @mittermichal (assuming that this is what's actually happening).

**Comment by mittermichal** [comment]
So at my system CNQ3 links dynamically to SDL 2.0.10, which is different to ETL using SDL 2.0.12
I compiled SDL 2.0.12 and linked it to cnq3 with LD_PRELOAD, but raw input was still working fine. I will try to build ETL with SDL 2.0.10 I guess

**Comment by mittermichal** [comment]
want to clarify that I used the same SDL version but it worked different between CNQ3 and ETL

**Comment by mittermichal** [comment]
apparently ETL uses SDL 2.0.14 as its set to be downloaded in https://github.com/etlegacy/etlegacy-libs/blob/2b774f0193c979fb699448c70b398cb8a6c5e93f/CMakeLists.txt#L685-L695
so I tried running CNQ3 with SDL 2.0.14 but raw input still works fine with it.

**Comment by mittermichal** [comment]
tried building ETL with SDL 2.0.10, issue stayed

**Comment by Aciz** [comment]
SDL has been upgraded to 2.0.16, is the issue still there?

**Comment by mittermichal** [comment]
yes

**Comment by ensiform** [comment]
Could it be something about using compiled version from etlegacy-libs that isn't enabling proper raw input for that Ubuntu version? Instead of using the system compiled lib?

Edit: it looks like the cmake script on the libs repo is intentionally disabling x11 xinput which could be the problem.

**Comment by mittermichal** [comment]
Thank for suggestion.
So I should try to use system installed libSDL?
How do I disable bundling libSDL during compilation?

**Comment by ensiform** [comment]
One of the legacy devs will have to assist with that.

**Comment by rmarquis** [comment]
Yes. Assuming you're using easybuild.sh, you can try `./easybuild.sh -64 -systemlibs`.
Otherwise the README has some more information.

**Comment by rmarquis** [comment]
Looks like `VIDEO_X11_XINPUT` has been first explicitly disabled in this commit: https://github.com/etlegacy/etlegacy-libs/commit/c12ad8df240c5ce540d8e278fc8df1477939e1c8. This is related to RPi, but I am not sure if that's really intentional.

If you get positive result with system libs, we can indeed try to reenable this for Linux builds.

**Comment by mittermichal** [comment]
@rmarquis yes, enabling `VIDEO_X11_XINPUT` solves the issue for me :)

**Comment by ensiform** [comment]
So there should not be any forced flags different from official builds of SDL on Linux platforms.

**Comment by rmarquis** [comment]
X11 input is now enabled again for Linux build.

@ensiform Thanks for pointing us in the right direction! And I was wondering all that time if Wayland or some new stuff wasn't responsible for the issue...

@techyian I am not sure if disabling `VIDEO_X11_XINPUT` was done on purpose, so in doubt I kept it disabled for RPi build. Let us know if that could also potentially fix the same issue on RPi, in which case we can adjust the relevant cmake code.

**Comment by techyian** [comment]
@rmarquis - I can't quite remember the issue caused by having X11_XINPUT enabled was but it certainly fixed an issue on the RPi. I would recommend keeping it disabled specifically for the RPi.

**Comment by rmarquis** [comment]
Perfect then! We can close the ticket as soon as @mittermichal confirms the issue is properly fixed with a new build - just to be extra sure for the release.

**Comment by rafal1137** [comment]
@techyian Out of the topic here. But I am having difficulties with building an package for RPI Release 2.78. It does complain about `GL_COMPRESSED_RGBA_S3TC_DXT1_EXT` being undeclared in rendererGLES.
PS: I am building it using docker container. GLES libs/development files are installed.

**Comment by techyian** [comment]
@rafal1137 - it's likely that the GLES package for RPi does not support it as the RPi package contains a subset of functionality. When I did the work for #885 I removed the case statement containing `GL_COMPRESSED_RGBA_S3TC_DXT1_EXT` but it appears to have been re-added since. I can't remember if we ever made a specific `ifdef` for RPI, but I would suggest wrapping it in a check for RPi if the rendererGLES code needs it for Android.

**Comment by rmarquis** [comment]
Looks like it's been readded in 4f253fb3c0434d20481bf205c4912e2fd47e0ae1.

As a global note, which might or might not be relevant here: S3TC used to require an additional specific lib to make it work on Intel cards (or we'd otherwise have a black screen), but this has been implemented by default in mesa directly for a few years now. So the added code might indeed be removed without any drawback (disclaimer: I know nothing about RPi and Android, so take that info for what it's worth).

**Comment by mittermichal** [comment]
took me few tries to build it properly but I can finally say its properly fixed.
1st I didn't update libs repo, then I had old CMakeCache.txt... :)

**Comment by mittermichal** [comment]
I tried it with official 2.78 installation and its not raw again.

**Comment by mittermichal** [comment]
libSDL is bundled:
```
ldd /usr/local/games/enemy-territory/etl
	linux-vdso.so.1 (0x00007ffc1d152000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0ca542e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0ca5423000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0ca5401000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0ca51e8000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0ca509a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0ca507f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0ca4e91000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0ca544e000

/usr/local/games/enemy-territory/etl --version
Client: ET Legacy v2.78.0 linux-x86_64 Oct  1 2021
Masked as: ET 2.60b linux-x86_64 May  8 2006
Built: 2021-10-01T19:50:51 UTC
```

**Comment by mittermichal** [comment]
could it be that cmake LINUX variable doesn't exist?
https://github.com/etlegacy/etlegacy-libs/blob/4666adc972ce6d007123e4c19190cdb1a4382b8f/CMakeLists.txt#L680
only UNIX listed here:
https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html

**Comment by ensiform** [comment]
I don't see it in the legacy cmake as such either so you are probably correct

**Comment by rmarquis** [comment]
I am not sure what's going wrong here. The official release and snapshots are built in a container with CentOS 7.9 with Wayland enabled (see b79feab928e416be9145235efba0b97b9fb17836 and 2f8bb9ae06f2bf14d01445cbc6de7107e1660670).

I'm looking at the build log of the official release, and indeed `VIDEO_X11_XINPUT` is *not* enabled:

[GH action log for 2.78](https://github.com/etlegacy/etlegacy/runs/3770814591):
```
[ ... ]
--   VIDEO_WAYLAND_QT_TOUCH (Wanted: ON): ON
--   VIDEO_X11              (Wanted: ON): ON
--   VIDEO_X11_XCURSOR      (Wanted: ON): ON
--   VIDEO_X11_XINERAMA     (Wanted: ON): ON
**--   VIDEO_X11_XINPUT       (Wanted: ON): OFF**
--   VIDEO_X11_XRANDR       (Wanted: ON): ON
--   VIDEO_X11_XSCRNSAVER   (Wanted: ON): ON
--   VIDEO_X11_XSHAPE       (Wanted: ON): ON
--   VIDEO_X11_XVM          (Wanted: ON): ON
--   WASAPI                 (Wanted: OFF): OFF
--   WAYLAND_LIBDECOR       (Wanted: ON): OFF
--   WAYLAND_SHARED         (Wanted: ON): ON
--   X11_SHARED             (Wanted: ON): ON
--   XINPUT                 (Wanted: OFF): OFF
```

On my Arch/WSL, that option is as expected set to ON in log, as it is now default.
The libs cloned in the CentOS container seems correct too:

```
  Cloning into '/__w/etlegacy/etlegacy/libs'...
  Submodule path 'libs': checked out '4666adc972ce6d007123e4c19190cdb1a4382b8f'
```

So it seems the issue is indeed fixed in the code, but something went wrong in the building process.

Edit:
> could it be that cmake LINUX variable doesn't exist?

Hu, that might be it. It doesn't explain why it works on some machine when self compiling (like mine or yours), but maybe that's an issue due to old packages on CentOS. Wouldn't be the first time we have such issue.

**Comment by rmarquis** [comment]
Actually the `VIDEO_X11_XINPUT       (Wanted: ON): OFF` makes me think the option was correctly detected as initially enabled, but was turned off by cmake for some reason.
I'll try to build a new snapshot with the UNIX fix, see what happens.

**Comment by rmarquis** [comment]
The new build also disabled Xinput, but I found the reason while looking at SDL cmake code: There is a missing lib that isn't installed on the container, so cmake turns the option off automatically.

```
check_include_file(X11/extensions/XInput2.h HAVE_XINPUT2_H)
...
     if(VIDEO_X11_XINPUT AND HAVE_XINPUT2_H)
        set(HAVE_VIDEO_X11_XINPUT TRUE)
...
```

In the log:
```
-- Looking for X11/extensions/XInput2.h - not found
``` 

And `HAVE_VIDEO_X11_XINPUT` is never set to TRUE.

We just need to find what Xserver package is providing this file.

**Comment by rmarquis** [comment]
The docker issue should be fixed now, but I think the docker container has to be updated manually before GH action can use it. @jackeri might help here.

**Comment by ensiform** [comment]
For reference, the SDL2 builder for Linux pulls all of these libs

See Linux step @  https://github.com/libsdl-org/SDL/blob/main/.github/workflows/main.yml

**Comment by rmarquis** [comment]
The docker image seems to have been updated a few days ago, but `VIDEO_X11_XINPUT` is still automatically disabled by cmake, and this issue persists in latest snapshot builds.

Can someone ping @jackeri on discord? I am not sure if docker has been properly updated yet, or if there is still something else to be done here.

**Comment by jackeri** [comment]
The image is not updated (by me atleast), Ill build a new image and update it to the hub today.

**Comment by jackeri** [comment]
I ended setting up a github action to do it for us. Basically when ever the build.Dockerfile changes now the image gets built and pushed to the docker hub.

https://github.com/etlegacy/etlegacy/actions/workflows/lnx-build-machine.yml

Will update the engine build to use the latest tag instead.

**Comment by rmarquis** [comment]
Nice! The more automated, the better.

The snapshot that is currently building now found the required lib and `HAVE_VIDEO_X11_XINPUT` is correctly set to true. Closing.
