### ISSUE TITLE
Update SDL to 2.0.16

### ISSUE THREAD

**Issue by Eonfge** [etlegacy/etlegacy#1730]
Last month, a new release of SDL came out, 2.0.16. It comes with some very significant Linux improvements;
- Significantly better wayland support
- Pipewire audio support
- Additional game controller support

If you could update SDL to 2.0.16, that would be great.
https://libsdl.org/download-2.0.php

As for urgency, right now I haven't seen any complaints and/or issues with SDL 2.0.14.

**Comment by rmarquis** [comment]
Yep, will do.

@rafal1137 Is there a specific reason you reverted your last libs commit in 2ec024f8e7c2f07cbde9e017ded33556ebf1a4e3?
Just so I know what to do to update the libs further.

**Comment by rafal1137** [comment]
@rmarquis The reason why I did reverted libs to this commit was "The changes I made was causing compilation issues on our build pipeline". Commits after this one I reverted too can be completly reverted on libs repo.

**Comment by rmarquis** [comment]
Jeez. Compilation chokes on Linux 64bit with

```
make[2]: *** No rule to make target `libs/sdl2/lib/libSDL2.a', needed by `etl'.  Stop.
```

See latest ETLBuild GH action. I'm at a loss here. Compiles fine on other platforms, including Linux 32 bit.

**Comment by Eonfge** [comment]
For [me and Flathub](https://www.flathub.org/apps/details/com.etlegacy.ETLegacy), that's actually of no concern to me, I package the 32bit version for better mod-compatibility ;)

But yeah, the whole cross-platform side-by-side compilation thing is a shitshow. I don't actually have much experience compiling SDL 2, so You'll need to ask around for people who can help you with that.

**Comment by rmarquis** [comment]
Yeah, but it's kinda important that it works for a new release, ya know :)

Anyway, just tried locally (64 bit build with Arch/WSL) and it works without any single issue... God I hate multi-platform support.

**Comment by rmarquis** [comment]
@rafal1137 Since I can't reproduce on Arch/WSL, do you mind having a quick look? I wonder if you'd get an error when building for 64 bit with latest bundled libs.

Anyone with some native Linux can join the party. The `./easybuild.sh -64` command should be enough to compile.

Worst case is we ship 2.78 with SDL 2.0.14, but it'd be great to have that issue sorted out.

**Comment by Aciz** [comment]
Built "fine" for me (after installing bunch of libs that my laptop was missing) on Ubuntu 20.04.2 LTS.

**Comment by rafal1137** [comment]
@rmarquis Yeah just compile 64bit on Manjaro and I was suprised that it compiled.

**Comment by rmarquis** [comment]
Possible commits of interest: https://github.com/libsdl-org/SDL/commit/6956f4aa1982b66b234026b46f7bb2dd44c67894 and https://github.com/libsdl-org/SDL/commit/ea9bece5ed4e76b6636d941101923487a6378ca6

~~Also, cmake ships a `FindSDL.cmake` by default (see [here](https://github.com/Kitware/CMake/blob/master/Modules/FindSDL.cmake)), so using our own unmaintained version might be the reason stuff breaks. Consider dropping our own soup if the required minimal cmake version is okay, otherwise try to port the latest changes in our own file.

Edit: nvm, the official Kitware file is only for SDL1.~~ Not actually relevant for bundled libs, my mistake meh.

Edit2: looks like the responsible commit:

> Installing: /__w/etlegacy/etlegacy/build/libs/sdl2/lib64/libSDL2.a
> ...
> gmake[2]: *** No rule to make target `libs/sdl2/lib/libSDL2.a', needed by `etl'.  Stop.

**Comment by rmarquis** [comment]
Latest libs change seems to break msvc compilation (meh), but I'll wait for the ETLBuild pipeline to finish to see if it actually fixes what appears to be a CentOS 7 specific issue.

**Comment by ensiform** [comment]
SDL2 in cmake for find package doesn't use an actual cmake script anymore, it uses some built in pkg config like scanning for unknown libs. However this does break on some Linux distros like Manjaro.

Check for SDL specific stuff in the ETe cmake script for how it works there.

**Comment by rmarquis** [comment]
Thanks. The issue isn't actually related to cmake find_package, since that applies to system libs only, but it is related to building bundled libs.

I'm however not happy with that ugly `FindSDL2.cmake` file, so I'll also have a look at your solution to get thing cleaned out.

**Comment by rmarquis** [comment]
SDL 2.0.16 is now properly integrated.

Let's track that cmake cleanup in a separate ticket.
