### ISSUE TITLE
Make players that `/selfkill` more visible with an icon

### ISSUE THREAD

**Issue by rmarquis** [etlegacy/etlegacy#1748]
Following discussion in #1742, it seems there is a need to make players that `/selfkill` more apparent.

> There has been a lot of complaints from the competitive community about these [selfkill] animations. There are two main issues:
> 
> * Player do not notice that their opponent selfkills in a gunfight, as the body doesn't instantly go into ground like in other mods, but instead slowly falls on it's knees, then ground, making players waste bullets on people who are already dead.
> * Proned players are hard to distinguish from players who have selfkilled, as their stance is very similar.

As an alternative to the ugly comp-centric proposed solution, display some voicechat icon above players that selfkill (with f.e. a skull icon) which should also be useful for public play. A similar idea could potentially also be used for downed players that go to limbo.

**Comment by Aciz** [comment]
I threw together a quick mockup (in Premiere, no actual code involved) of a possible implementation, but I don't know if this is too intrusive.

https://streamable.com/4oxnpe

**Comment by rmarquis** [comment]
@bystry Since I see a thumb down but no further explanation, I kinda have to ask: is there anything technical that would make the above not viable?

More globally: I know we definitely don't get along and have a level of mutal repect at near zero, and that you might interpret whatever I write in the most negative way possible. I used some colourful words in the other threads, but I hoped the context would make clear the idea I was trying to convey.

It's unfortunate that the comp community isn't always very open to change, and true that dealing with it is sometimes is like "banging your head against a wall" (not my own words, so that should tell something). When people aren't even taking the time to understand the raised issue and demand cheap and subpart solutions, I am not sure what can be done beside taking notes of the complaint, but still trying to come up with ideas and iterating over a possibly better solution, as opposed to immediately implementing a 2006 status quo that might not be ideal. Legacy would *never* have gone that far if we aimed for easy and quick solutions. Somehow, all that hard work is finally starting to pay off, even for comp. Maybe try to get a little bit patient, and understand that exploring alternative solution might actually be worth it on the longer term?

My apologies for the noise, in case I misinterpreted the thumb down.

**Comment by zenixje** [comment]
As comp player I don't see any reason to implement this. And I think 99% of competitive players wil agree with me.
The current animation situation is a lot better, especially with the changes made by Aciz. Selfkilling is something that is primary used in the competitive community. 

The comp community is open to change. I can list some changes as a ET player from etmain, to ETPro  Between 2004-2010 we had many changes
- XP rewards removed, this was a huge change that many people did not like
- from 6on6 to 5on5 and back. 3on3 was implemented.
- mortar removed, also pretty big change.
- hitsounds implemented
- mines reduced
- etc...
- the only original map that is left in the current mappool is radar. Because we ported RTCW maps and tried many new maps, those are all changes.

As you can see, during the development cycle of ETPro many changes got implemented and accepted by the community. This was because the creator of the mod listened to his community and also had competitive players in his team.

I see the same thing (partly) now with Legacy. Devs like Aciz and ryzyk-krzysiek for example are active on the Discord and everyday they are helping us to improve this game from the competitive side. We try to provide feedback and test things out during gathers. Another example are ET Legacy maps, Since this week we using the ETL maps in matches and we have collected feedback for Kemon and he already implemented some changes. This is a community working together and trying improve the game that they all love. We played those original maps for more than 15 years. Many players did not play ET Legacy until a few weeks ago, but are now playing ETL maps and are giving feedback on them. I don't know many communicaties that can handle so many changes in such a short while.  Making the switch is already a huge change. It takes effort to change all your configuration and get used to legacy.

The reason the ETPro players are playing legacy now is a combination of factors, for me these are the primary factors as a player:
- ET:Legacy Scrim Discord
- Tournaments
- 250 FPS
- sv_fps 40
- hitboxes are better

We did not had much reason to leave ETPro before, we had all the options we needed (with some broken things we got used too) and a huge feature was ETTV. Since streaming is now mainstream, ETTV is not that important anymore.  But if we had 250fps and fixed hitboxes we would not have switched, because there would not have been a reason too. Competitive players are FPS junkies and are happy to use the expensive monitors with a higher refresh rate in this old game.

Also tournaments are a huge factor to attract players, all tournaments had ETpro as primary mod. If the legacy team would have hosted some tournaments and posted that on the competitive websites (crossfire.nu) we would have made the switch earlier perhaps. There was no competition, so not reason to switch. The tournaments from the Scrim Discord are a driving factor behind this.

Another factor was, the legacy team did not have active competitive players How can you convince a community to switch to your mod if you are not a part of that community? With the efforts of the ET:Legacy Scrim Discord and several devs that has changed now.

And the banging against the wall is just misunderstanding from both sides. You don't know the competitive community and we don't know you and that has been the case for legacy for way too long. Mutual misunderstanding. With the help of the devs I mentioned before and the ET:Legacy Scrim Discord admins this has improved. But it's still there. And it will take effort to correct that.

**Comment by rmarquis** [comment]
> As comp player I don't see any reason to implement this.

Just to confirm this isn't a typo and clear any confusion, are you saying there is *no* need for this feature anymore, as the recent change for selfkill animation (dcb7d055dbdbc323419f62bf56ff21c578c33267) is good enough?

Otherwise, I'm very, very glad to read your message!

It took a lot of time to get where Legacy is today, with lot of trial and error. It also took time to "catch up" to etpro level, with sometimes the need to 'reverse-engineer' how some feature work because they were really badly documented. Legacy has been known in the etpro community for a long time too (at least by quite a few veterans), and quite criticized in a negative way - sometime justifiably considering what was still missing, sometimes not because etpro was kinda seen as the unmatchable holy grail. I'm glad to see its reputation changing and the wind turning.

**Comment by Vorschreibung** [comment]
AFAIS this issue can be closed at this point
