### ISSUE TITLE
Make movers and doors push players and items instead of crushing them

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1754]
As far as I understand it correctly, crushing players and items by movers and items is not a bug, but rather an intended behavior from vanilla. This mechanic often breaks the game in some aspects:
- it is not possible to hide in a moving truck (prime example is supply truck with gold bars in it, other can be goldrush);
- players get crushed accidentally when approaching the mover (truck, tank on goldrush) sometimes resulting in wasted seconds when that particular player is the only one moving the truck/tank;
- items such as weapons get wasted when left near doors;
- apart from having a huge impact on the gameplay, this mechanic also issimply very frustrating.

Thus, I suggest changing this mechanic to ETPro's (and possibly other mods) behavior - push players/items instead of crushing them. This will result in an improved competitive gameplay

**Comment by rmarquis** [comment]
I'd suggest keeping the crush if proning in front of movers, but not in other positions. Should definitely remove the crush by doors, yep.

**Comment by ryzyk-krzysiek** [comment]
> I'd suggest keeping the crush if proning in front of movers

Afaik that's how it is supposed to work right now and fixing it might be quite hard I think.

Here we check if groundEntity is pusher so it should exclude crushing when we are on the truck and not on ground.

https://github.com/etlegacy/etlegacy/blob/54ca359c71d93cd9fde04e7ee70bb741dc0d23db/src/game/g_mover.c#L651

But we get killed when truck is going uphill or downhill, because of how steep it is the groundEntity is set to `ENTITYNUM_NONE`.

https://github.com/etlegacy/etlegacy/blob/54ca359c71d93cd9fde04e7ee70bb741dc0d23db/src/game/bg_pmove.c#L1895-L1907

We get killed when truck has gold in it and because we are not standing on the gold so when we get pushed around in the truck at some point the gold will want to push us and instead will kill us.

**Comment by Aciz** [comment]
Just a note, I don't know if `func_door` goes through the code that's relevant for this issue, but it has a specific feature to crush players instead of reopening when getting stuck by players. So incase it uses the same code, it should be made sure that this functionality remains.

![image](https://user-images.githubusercontent.com/14221121/138859972-1384d57e-c572-4d30-98fc-bdcfe0771759.png)

**Comment by ryzyk-krzysiek** [comment]
At first thought that sounds like something else because here it is coded to kill players when dead or prone only

https://github.com/etlegacy/etlegacy/blob/54ca359c71d93cd9fde04e7ee70bb741dc0d23db/src/game/g_mover.c#L653-L659

**Comment by Aciz** [comment]
Implemented in 01ecf195dfc063aca05882ec4c09fefffe8f8cf1
