### ISSUE TITLE
Improve MISSION TIME display functionality in scoreboard and in HUD during warmup

### ISSUE THREAD

**Issue by BystryPL** [etlegacy/etlegacy#1756]
Currently in stopwatch mode in the scoreboard before 1st and 2nd round during warmup in "MISSION TIME" field "WARMUP" is displayed. Current behavior doesn't give the players any clue about the actual mission time and about the  time set during 1st round. 

This could be improved, in a way that it would display during warmup in "MISSION TIME" field:
- full mission time - before 1st round;
- mission time set after 1st round - before 2nd round;

Before 2nd round it could display either only the set time (for instance 4:32), or set time slash full map time (for instance 4:32/10:00). I did a simple mockup (yes, big photoshop skills) how I imagine it would look. 

**Before 1st round**
![shot0038-kopia](https://user-images.githubusercontent.com/45846431/135654122-7aad7aa6-5833-470f-b9bd-1b94e330adca.png)

**Before 2nd round**
![shot0040-kopia](https://user-images.githubusercontent.com/45846431/135654227-b91bb6c2-4f7d-4b61-ab55-99366bb586e8.png)

The same could be then done in the HUD:
![shot0043-kopia](https://user-images.githubusercontent.com/45846431/135655097-2597f4c1-385e-48ef-ba51-26082b2b748a.png)

That's roughly it, let me know if you guys have any other ideas regarding this feature.

**Comment by rmarquis** [comment]
I've quickly looked into it, and it seems the full map time isn't passed to the second round. That information isn't relevant anyway, and the resulting code is also simpler/cleaner, since it applies to all game mode.

Closing now.

**Comment by BystryPL** [comment]
Thank you for adding this! I really like this feature.

**Comment by rmarquis** [comment]
Thanks to you for suggesting it!

**Comment by BystryPL** [comment]
The behavior seems to be buggy, unless I'm missing something on those pictures below. Original time 4:52, objective reached in 4:08 in second round. Information on the scoreboard, however, says that allies successfully beat the clock by 1:24. See below.
![Zrzut ekranu 2021-10-13 o 19 47 39](https://user-images.githubusercontent.com/45846431/137186453-6b5b4513-5b3f-4553-872e-d8a947c75126.png)
![Zrzut ekranu 2021-10-13 o 19 47 53](https://user-images.githubusercontent.com/45846431/137186517-9226b1ee-3f50-49c0-b3c1-7cb11d6e4edf.png)

**Comment by BystryPL** [comment]
Also see the relevant Twitch clip where it happened: https://clips.twitch.tv/HelpfulLongCardKevinTurtle-ogdZXCRdrPSod8YF

**Comment by rmarquis** [comment]
Moved the above to #495.

**Comment by BystryPL** [comment]
There is a bug regarding this feature: when changing configs during warmup (for instance from legacy3 to legacy6), which which causes the timelimit to change, the time displayed in the HUD doesn't change, it stays the same. It changes only after starting the match. 

For instance, how to reproduce on supply: 
1/ change config to legacy3 - timelimit of the map is set to 12:00;
2/ change config to legacy6 - timelimit of the map is set to 15:00, but the time displayed in the HUD is still 12:00.

**Comment by rmarquis** [comment]
For the timelimit to propagate correctly, the game needs to be reinitialized, which is usually done but not always.
There are cases where this isn't done (on purpose), and this explains why the timelimit doesn't propagate until the actual start of the game.

The root of the issue is located in `SV_CheckTransitionGameState()`, in the first condition:

```
	if (old_gs == new_gs && new_gs != GS_PLAYING)
	{
		return qfalse;
	}
```

Adding some condition for SW game mode here feels really dirty (game code in server code), so I'll see if there is cleaner way to handling this.

**Comment by BystryPL** [comment]
If you check ETPro for instance, you'll see that changing the config always makes the game reset (or restarts map, I don't now exactly, but it "resets" the map somehow), which isn't the case in legacy. Maybe that could be of any help.

**Comment by rmarquis** [comment]
Yes, the above is simply the reason it happens.

The `map_restart` command is initially called from `G_configSet()` in the mod code, so that's the better place to implement a fix.

**Comment by rmarquis** [comment]
I am not sure what magic etpro does with its restart code (the topic came a few times in the past afair), but the issue should now be fixed in Legacy.

It's a bit hacky, but since it's small visual issue in warmup only it doesn't really matter. Also fixed the team spawntimers the same way, in case configs use different values for a map.

**Comment by ryzyk-krzysiek** [comment]
It could be that in etpro they call `GS_RESET` instead of `GS_WARMUP` in `G_configSet` as it will force the `SV_MapRestart_f` and still change the gamestate to warmup. It seems to work but I don't know if it entails some unwanted changes and I will not test further myself as you already fixed it anyway.

https://github.com/etlegacy/etlegacy/blob/e1e9cd412c0b1cafc0acb9d5ce14f04d8a8c379b/src/game/g_config.c#L524-L527

https://github.com/etlegacy/etlegacy/blob/7834fc5962e555e4f40dd66b07ae654ca7560cc5/src/server/sv_ccmds.c#L201-L223

**Comment by rmarquis** [comment]
This seems to be the right way to do it, yes!

Like you, however, I am not sure if there would be some unwanted side effect, so I'd suggest:
* release 0.28.1 as it is now
* change to cleaner GS_RESET right after for 2.79, so we'll get a more testing without the need to delay the hotfix further
