### ISSUE TITLE
Client crashes when dynamite explosives 

### ISSUE THREAD

**Issue by Minimuppet** [etlegacy/etlegacy#1777]
Large amount of clients are crashing to their desktop on certain map when dynamite explodes. eg erderberg when blowing second gun, goldrush I think second barrier and aldernest when controls are blown.

**Comment by Helldembez** [comment]
Over on discord people tried to reproduce it by playing on the server, but they did not encounter it. This at least means it's not so frequent. This doesn't mean that it shouldn't be fixed asap, but at least gives some room for investigation. 

My first thought is this has something to do with dynamite chaining? However, on the competitive side I haven't seen any reports yet. Aciz will try to play through debugging client. If a consistent reproduction path can be found please let us know.

**Comment by rmarquis** [comment]
I can't reproduce this issue when planting several dyna. I kinda doubt the issue is related to the latest dyna chaining changes, as the behaviour hasn't been really modified (extra dyna removed instead of exploded by default).

This however makes me think about the infamous oasis wall bug we had several years ago (#627), which was related to a sound issue when compiled with a specific compiler. For 2.78, the default sound engine has been changed from OpenAL to SDL again. Might be something here.

**Comment by ryzyk-krzysiek** [comment]
First reports of something like this occurring were like 2-3 months ago, so changes to dynamite chaining shouldn't matter. Also I believe if it was a server side issue either server would crash or everyone on the server would.

This crashing never happens on scrim servers too and there are played all 3 mentioned maps regularly. My only suspicion before was `cg_drawEnvAwareness` as it is forced off on scrims, but recent changes probably exclude it as being the probable cause of crash.

**Comment by rmarquis** [comment]
Potentially fixed by 0ff8a24065d368423758a421ca0b285a4c7334e7.

**Comment by randomek** [comment]
I had it just 2 times but only after upgrade to 2.78 and it's very hard to reproduce. In logs it looks like normal: "Client shutdown" but today someone who was playing with me ask if someone experienced that issue exactly at that same time when my Client shutdown. Today it was 1 second after winning the game and dyna on fuel dump blow up. But first time wasn't with dyna related.
