### ISSUE TITLE
Make fireteam `selectbuddy` command persistent between map changes

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#1791]
Right now when map changes the selected fireteam members will be reset and players need to select them again. (in etpro it is persistent)

**Comment by Aciz** [comment]
2 ways to go on about this:

1. Use up one of `ps->persistant` field to store this data (there's a finite amount of these and more cannot be added in order to retain backwards compatibility), there are few free and unused though.
2. Keep track of selected fireteam members with a pseudo cvar, since that will automatically carry through map changes, only problem is that since this would have to be cleared upon shutdown on cgame, which means that `vid_restart` would reset it.
