### ISSUE TITLE
Add pb_sv_getss alternative

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#1942]
"PB_SV_GetSs [player_name_or_slot#]
Sends a request to all applicable connected players asking for a screen shot to be captured and sent to the PB Server"

**Comment by rafal1137** [comment]
Do not you know that PB does not support ET at all anymore ?
Thus sending screenshots to PB Servers never gonna happen.

Marking this as invalid and closing

**Comment by Aciz** [comment]
He's talking about ALTERNATIVE to this, ofc PB is and never will be supported.

**Comment by x0rnn** [comment]
Yea, I didn't mean sending it to a PB server, but saved in a directory on the gameserver...

**Comment by HeDo88TH** [comment]
This could be a good step forward in cheat detection. But I wonder if we should impose some sort of "client certification" in order to connect to the game servers. That way someone could just edit the source code, recompile it, and play with a rogue client. I don't know if anyone is already doing this, but this is a threat that we absolutely need to consider.
We can also add all pb functionality within the legacy client, but that won't stop any determined cheaters from doing what I just pointed out.

**Comment by x0rnn** [comment]
Yea, I was thinking, if this is open source, anyone could just modify the client so it would send clean screenshots I suppose...

**Comment by ensiform** [comment]
> This could be a good step forward in cheat detection. But I wonder if we should impose some sort of "client certification" in order to connect to the game servers. That way someone could just edit the source code, recompile it, and play with a rogue client. I don't know if anyone is already doing this, but this is a threat that we absolutely need to consider.
> We can also add all pb functionality within the legacy client, but that won't stop any determined cheaters from doing what I just pointed out.


I think the best you can hope for is the server mod has authentication for client check for competitive servers but not enabled on public's. Which given enough crafty coding could still be circumvented but you'd keep the majority out. Such is the nature of open source/copyleft engine. You can't really include any closed parts. Also pretty sure GPL v3 closed some of the license loopholes which were doable with GPL v2 (Q3).

There is very little benefit to doing anticheat in such conditions because you'll only be stopping people who aren't determined to cheat.

Also, adding more features that lock players behind one engine is unfriendly to the spirit of open source in general imo.
