### ISSUE TITLE
Adjust default `cg_swingspeed` to better reflect actual player direction

### ISSUE THREAD

**Issue by Calinou** [etlegacy/etlegacy#1992]
[ET (like RTCW) defaults to `cg_swingSpeed 0.1`.](https://github.com/etlegacy/etlegacy/blob/b41b3c965ce8aba9e330d374f07b37fe092dc7d6/src/cgame/cg_main.c#L442) Quake 3 (and most other derivative games) used `cg_swingSpeed 0.3`. This cvar is used to smooth out third-person direction changes. Higher values result in more instant visual feedback, but (logically) look less smooth.

I've always found player animations to look a bit strange in ET when quickly changing directions (either when strafing during fights, or when players are sprinting to exit their spawn). I don't get the same impression in other Quake 3-based titles, which makes me think the swing speed value is too low.

Maybe we could consider using an intermediate value like `0.15` or `0.2`?

**Note:** `cg_swingSpeed` is cheat-protected, so you need to start a local server with `/devmap` or `/sv_cheats 1` to adjust it. Use `/cg_thirdPerson 1` then move around to see the effect of adjusting this cvar.

**Comment by Aciz** [comment]
So instead of changing what's been the default in the game for almost two decades, I'd be more in favor of unlocking the cvar, and limiting the range to `0.1-0.3` for example. Since it's purely client sided visual difference and doesn't affect hitboxes or anything, I see no real harm in allowing players to adjust the animation transition speed.

**Comment by mittermichal** [comment]
agree on unlocking the cvar
