### ISSUE TITLE
Medpack/ammopack throw distance not long enough for diagonal throw

### ISSUE THREAD

**Issue by oheikk** [etlegacy/etlegacy#2269]
You will catch your own med pack / ammo pack if you aim diagonally in relation to the grid. This is also an issue in Vanilla ET.

I'm not sure if this should be considered a bug or a feature.

![image](https://user-images.githubusercontent.com/107760898/220198207-a9d7cd24-ad8f-4617-b6d8-f4538405b7a2.png)

**Comment by ryzyk-krzysiek** [comment]
In my opinion this is vanilla ET feature. For collision detection with items bounding box is used instead of actual player capsule, this is why you can also pick up items through thin walls/doors.

As per VET comment:
> Items can be picked up without actually touching their physical bounds to make grabbing them easier 

https://github.com/etlegacy/etlegacy/blob/af544048b5c9ca82b29271015cfa818673e738f0/src/game/g_active.c#L474-L491

https://github.com/etlegacy/etlegacy/blob/af544048b5c9ca82b29271015cfa818673e738f0/src/game/bg_misc.c#L2521-L2547

**Comment by oheikk** [comment]
I wouldn't suggest changing the item pick-up code, but rather the medpack/ammopack throwing code to use the $L^\infty$ norm:
![image](https://user-images.githubusercontent.com/107760898/220207449-ec43a975-40aa-4df2-8292-ab10fb3e4776.png)

**Comment by oheikk** [comment]
Video for clarity because I realised the pictures might not be all that clear. _(edit: better video)_

https://user-images.githubusercontent.com/107760898/220313360-cf3ee150-38c7-4977-808c-e1742344d769.mp4
