### ISSUE TITLE
Add SSAA to ETL

### ISSUE THREAD

**Issue by u1ps** [etlegacy/etlegacy#2340]
Better quality on distant objects
<img width="651" alt="MSAA" src="https://github.com/etlegacy/etlegacy/assets/99591943/bba4a7a6-a6d4-4fd8-86a5-dabb78f5cd29">
<img width="656" alt="SSAA" src="https://github.com/etlegacy/etlegacy/assets/99591943/6b0f53bb-ff33-4c17-afa8-476519af84b9">

**Comment by Calinou** [comment]
Note that `r_scale` values above `1.0` can already be used for supersampling, but this approach is slower and not as stable at high native resolutions: https://github.com/etlegacy/etlegacy/pull/2546

16x MSAA is usually significantly faster than `r_scale 2.0` and 4x MSAA due to the graphics driver implementing SSAA in a more optimized manner. On top of that, it results in better quality for supersampling as driver SSAA will use MSAA's rotation pattern, while using `r_scale 2.0` displays the viewport texture with box filtering (which isn't as good).
