### ISSUE TITLE
Show last 8 characters of GUID instead of first 8 in /players

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2369]
As per the title, to make it consistent with WolfAdmin's /listplayers, /list and PunkBuster's /pb_plist. No idea why someone decided to use the first 8...

Fix is here: https://github.com/etlegacy/etlegacy/pull/2355

Although not sure what happens if there is no GUID, probably just prints the *.

**Comment by rmarquis** [comment]
As far as I remember, there is a technical reason for this choice. I don't remember the specifics (I vaguely remember it being related to Omnibot, but that might be something else). There's probably a ticket or commit where this is documented.

Also remember having discussed this with the author of Wolfadmin, and my understanding was that this would be changed on WolfAdmin side (which never happened I guess).

**Comment by rmarquis** [comment]
The development version of WolfAdmin actually changed the GUID characters [here](https://github.com/etlegacy/wolfadmin/commit/9eb7e316b1ccb42652a2446bdf3b674fc20d9f57) - so Timo did indeed change it.

Since ETL ships a slightly modified fork of WA (to simplify installation), this could be included in the shipped version.
