### ISSUE TITLE
Different gun position between ETL and other mods

### ISSUE THREAD

**Issue by hkly-1245** [etlegacy/etlegacy#2388]
### description of the issue (current behavior, expected/desired behavior)
ETL seems to feature a different, lower gun position compared to ~~2.6b~~ other mods. It is not related to fov or resolution. 
Legacy
![image](https://github.com/etlegacy/etlegacy/assets/133721553/e5f06a95-55f2-488e-868c-8f0217dc2fc6)

~~2.6b~~ other mods
![image](https://github.com/etlegacy/etlegacy/assets/133721553/ea8c74d8-c186-4138-bf3a-f23b4970efd3)

It can however somehow be "fixed" by applying `cg_gunz 3` or any value closer to this. 

Could it be fixed by shipping a default value closer to 3? or does it need to be tweaked somewere else? 

### minimal steps to reproduce the problem
Compare screenshot to screenshot the two version with the same 'r_mode' and 'cg_fov'
### motivation and use case for changing the behavior
Get closer to the original look and feel
### version used
ETL 2.81

**Comment by ryzyk-krzysiek** [comment]
It is mod related not engine, so ET 2.6b or ETL it makes no difference.

Legacy mod fov calculation was specifically changed to what more modern games use for better experience on widescreen monitors. (If you use 4:3 aspect ratio then your fov is unchanged IIRC).

Gun viewmodel _is_ affected by fov: https://github.com/etlegacy/etlegacy/blob/6c744248a8d2fa9469ef3d5418d4130378993996/src/cgame/cg_weapons.c#L3849-L3857

Because of the fov calculation changes (among other reasons) legacy mod has unlocked `cg_gunZ/X/Y` cvars and lowered possible `cg_fov` to `75` so it is possible to play with the "same" settings as other mods that still use `etmain` fov calculation, most notably `ETPro`.

I don't see the point in changing the default value at this point. Anyone can change the `cg_gunZ/X/Y` cvar values to get the best own experience. There was also introduced `cg_weapAnims` cvar to enable/disable selected weapon animations.
