### ISSUE TITLE
vchat/vtchat/vbchat lua implementation is broken, custom message does not work

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2411]
`vtchat VoiceOnly ClientNum 50 Vsay-String X-Location Y-Location Z-Location Vsay-Number \"Custom-Message\"`

Custom message does not work, and the default message is always colored ^2.

**Comment by oheikk** [comment]
I would argue the implementation is not broken, but the Lua documentation is wrong. There's no support for `Vsay-Number` behaviour in the game at all, and the `Custom-Message` behaviour is done server-side before sending the `vchat` command to the client. The documentation also doesn't say what the magic-looking number `50` is doing in the examples. It's the colour code in decimal ASCII (the ASCII value of '2' is 50 which is why you get green).

You can get the exact same behaviour with Lua, if you replicate what the server does. For example, `vtchat 0 7 53 enemydisguised 123 -456 789` would send the correctly coloured `vtchat` "Enemy in disguise!" as if sent by client 7.

To get the `Custom-Message` behaviour, you need to do something like:
```lua
-- color 50 here doesn't matter but need to pass in something
et.trap_SendServerCommand(-1, "vchat 1 3 50 cheer")
et.G_Say(3, et.SAY_ALL, "Yippee!")
```
That's a more or less direct Lua equivalent of what the server does when a client sends `vsay cheer Yippee!`

The Lua documentation for `vchat` etc. needs to be fixed, but before that is done, I'd argue the current `vsay` etc. implementation as a whole needs a little bit of work done on it. If I recall, etjump does it quite well with custom messages, vsay number etc. Could just use their implementation and adapt the Lua on top of that.

**Comment by Aciz** [comment]
FWIW our custom vsay implementation in ETJump is not perfect either, it is straight up broken with fireteam vsays since the beginning because they can have anywhere between 3-7 params IIRC, and our code doesn't parse that correctly.

**Comment by x0rnn** [comment]
The previous code example worked with ETPro, which is why I based my assumption the implementation is wrong (my etpro lua code does not work on legacy).

The extra parameter that is missing on legacy (Vsay-Number) selects the vsay variant if it has multiple sounds. Is it random on legacy or always the 1st?

**Comment by oheikk** [comment]
> The extra parameter that is missing on legacy (Vsay-Number) selects the vsay variant if it has multiple sounds. Is it random on legacy or always the 1st?

It's randomized on the client's side, like all vchats in legacy.

**Comment by x0rnn** [comment]
Problem with this method is it logs all chats as well, kinda spamming the log.
