### ISSUE TITLE
Fix scoped K43 and Garand recoil to 71 FPS physics

### ISSUE THREAD

**Issue by x0rnn** [etlegacy/etlegacy#2544]
Currently the recoil is between 71-125 FPS as per https://github.com/etlegacy/etlegacy/pull/1680. I'd argue this is a major nerf for those who were experienced snipers, whereas it changes nothing for the average sniper who always used 125 FPS.

Making the recoil equal to 71 FPS physics would make both experienced snipers as well as average/beginners happy/happier and improve their sniping.

In short, currently it's a major nerf and nobody is happy (except those who hate sniper), making it 71 would make everyone happy (except...) and buff the weapon for noobs a bit.

Refs https://github.com/etlegacy/etlegacy/issues/1796

**Comment by x0rnn** [comment]
For what it's worth, I tried reverting that commit and 71 fps recoil was still bigger than in etpro, so it's not that simple.

**Comment by x0rnn** [comment]
Also, for what it's worth, lots of things in legacy got changed or added due to feedback from the competitive scene, and although sniper itself is only occasionally seen in some maps in competitive matches, everyone who used it in etpro had it capped to 71 FPS.

**Comment by x0rnn** [comment]
@ryzyk-krzysiek the #1680 commit seems to be broken.

https://streamable.com/9zfwxu

The recoil is not fps independent anymore.

**Comment by Aciz** [comment]
It never was, this is normal. It was made close enough to be insignificant, but it was never quite perfect.

**Comment by ryzyk-krzysiek** [comment]
I think I was talking about it not being perfect while I was trying to fix it at the time on discord (not publicly). I think the whole function is inherently flawed and I didn't want to rework it at the time because it was too much work while I could make the difference pretty insignificant compared to ETMain/ETPro and I believed that recoil being random masks it decently.

> and although sniper itself is only occasionally seen in some maps in competitive matches

And changing it to 71 fps wouldn't have changed anything there and I still get killed in 1s like the recoil doesn't exist while the guy is one pixel on my screen and has no bullet damage drop off. I see no reason to decrease it.

**Comment by x0rnn** [comment]
> And changing it to 71 fps wouldn't have changed anything there

It changed it for the sniper; there is quite a difference between 100 and 71. Nerfed too much and a big regression compared to etpro. I'll post videos in the new issue I opened #2816. Also if it wouldn't have changed anything for the enemy dying, then there is equally no reason to not set it to 71 FPS.

**Comment by ryzyk-krzysiek** [comment]
> Also if it wouldn't have changed anything for the enemy dying, then there is equally no reason to not set it to 71 FPS.

But your comment that sniper is only occasionally seen in some maps implies that changing to 71 fps would help fix that, which is not true since people use sniper in comp the same way they did in etpro. If you bring sniper to 71 you should move pistol from 125 to 71 too since the only argument is that people used that in etpro.

**Comment by x0rnn** [comment]
There's a larger meta difference in playing sniper with 71 or 125 FPS than there is with pistols, it's literally game-changing.

**Comment by ryzyk-krzysiek** [comment]
And nobody ever complained about any of this bar few people from etpro. I don't know why I even try arguing, good luck.

**Comment by x0rnn** [comment]
Who else would complain? There are a few good snipers from etpro that migrated to legacy.
