### ISSUE TITLE
Cvops scope is up after revive

### ISSUE THREAD

**Issue by u1ps** [etlegacy/etlegacy#2637]
When Cvops gets killed while scope is up. After revive Cvops has scope up. (Should not be as damage unscopes, therefore getting killed should unscope)

**Comment by Vorschreibung** [comment]
Can't repro via `/revive 0` :thinking: - self damaging via nade while scoped also does not unscope :thinking:

**Comment by u1ps** [comment]
Can not either now. Happened in game patch 2.81.1. So conditions for this to happen have to be more specific :P ?

**Comment by u1ps** [comment]
It happens when u die while holding down fire

https://github.com/user-attachments/assets/6161675a-da6a-483d-a102-b93574b56e3c

**Comment by Aciz** [comment]
Correction: it happens if you're holding `+attack` when you get revived, it doesn't matter if you hold it while you die. This happens because holding down `+attack` when you respawn blocks `PM_Weapon` function from running, to prevent firing weapons immediately when spawning. When the button is held, the weapon in your playerstate doesn't correctly update the weapon since `PM_Weapon` does not run, and you retain the scope.

https://github.com/etlegacy/etlegacy/blob/7de06ccef18decd90304911fc19ba4284647d817/src/game/bg_pmove.c#L3355-L3371
