### ISSUE TITLE
/scores no longer works in snapshot v2.82.1-156g609fdca

### ISSUE THREAD

**Issue by csmaxpower** [etlegacy/etlegacy#2768]
I am assuming it is related to this new implementation of the command: [#2681]( https://github.com/etlegacy/etlegacy/pull/2681)

-  `/scores` now results in showing only the clients data who issued the command while in-game.  
- Full team data only shown after a match is complete (_in-between rounds did not result in a responsive command either_)

I have read the implementation notes, and understand that delay was supposed to have been introduced with the command now (per client updates to qagame), but this appears to be buggy (no responses ever) and not just delayed responses.

**Comment by ryzyk-krzysiek** [comment]
Demo would be appreciated because I cannot reproduce.

**Comment by csmaxpower** [comment]
[scores-cmd-demos.zip](https://github.com/user-attachments/files/16913228/scores-cmd-demos.zip)

**Comment by x0rnn** [comment]
![image](https://github.com/user-attachments/assets/a9045264-d1ea-49ac-9813-2b95bd2b819c)
"totals are there, but not players"
"statsdump in demo is ok" 

Related?

**Comment by ryzyk-krzysiek** [comment]
Thanks I think I figured it out. If guid starts with a number then the commands start being overwritten in cgame in command buffer, which is later used to display stats

https://github.com/etlegacy/etlegacy/blob/b85a8189f5eca74ff33216321a38194f2b41a098/src/cgame/cg_servercmds.c#L2915-L2919

Turns out `Q_atoi` is a big lie since if you give it a string `123scores command` it will return `123` while I was always expecting it to return 0 because the whole string is not a number, will have to see if there is a function that does that.

EDIT: So if guid starts with a number then it resets the scores count and every player before is not shown.

**Comment by ryzyk-krzysiek** [comment]
> "statsdump in demo is ok"

If demo shows them I would guess it is being watched with different mod version that doesn't have new handling, because I see no reason why it would work in demo but not live server.

**Comment by Aciz** [comment]
> Thanks I think I figured it out. If guid starts with a number then the commands start being overwritten in cgame in command buffer, which is later used to display stats
> 
> https://github.com/etlegacy/etlegacy/blob/b85a8189f5eca74ff33216321a38194f2b41a098/src/cgame/cg_servercmds.c#L2915-L2919
> 
> Turns out `Q_atoi` is a big lie since if you give it a string `123scores command` it will return `123` while I was always expecting it to return 0 because the whole string is not a number, will have to see if there is a function that does that.
> 
> EDIT: So if guid starts with a number then it resets the scores count and every player before is not shown.

You could loop through `str` and check with `Q_isnumeric`
