### ISSUE TITLE
Sniper desync

### ISSUE THREAD

**Issue by ryzyk-krzysiek** [etlegacy/etlegacy#2906]
https://github.com/user-attachments/assets/f4bfc9b9-885f-48df-ac77-d1b8e380f4e8

refs https://github.com/etlegacy/etlegacy/commit/b6727a981243f0aab23267dfe24d673714b36b99

**Comment by Aranud** [comment]
Just to ensure the information isn't lost, that's the wanted behaviour so we got the same behaviour as ETPro.
Now, we need to ensure this "desync" delay (the delay only) is keep so you still have time to run and shot right after scoping.
This is purely due to the latency between server and client. Still, we need to keep this delay to let the quick shot possible. 

This also introduce the 'ghost bullet" if you are firing quickly enough while scoping. You hear the firing but no bullet are out.
Finaly, it broke prediction. So this need to be adressed as well.

**Comment by x0rnn** [comment]
I think this can be closed now?
