### ISSUE TITLE
show delta time in debriefing in stopwatch mode

### ISSUE THREAD

**Issue by ETLegacyTeam** [etlegacy/etlegacy#495]
Author: @rmarquis (Spyhawk)
Date: 2014-01-28
Redmine Issue: 495, https://dev.etlegacy.com/issues/495

---

In stopwatch mode, some game are won be a very narrow margin. One thing I'd like to see is the delta time when the clock is beaten, as you currently have to check the in-game clock prior to the end of the round to have an idea - and not always possible when focusing on the game.

Ie, display "Allied beat the clock by 5 secs" in debriefing screen.

**Comment by rmarquis** [comment]
By @BystryPL:

The behavior seems to be buggy, unless I'm missing something on those pictures below. Original time 4:52, objective reached in 4:08 in second round. Information on the scoreboard, however, says that allies successfully beat the clock by 1:24. See below.
![Zrzut ekranu 2021-10-13 o 19 47 39](https://user-images.githubusercontent.com/45846431/137186453-6b5b4513-5b3f-4553-872e-d8a947c75126.png)
![Zrzut ekranu 2021-10-13 o 19 47 53](https://user-images.githubusercontent.com/45846431/137186517-9226b1ee-3f50-49c0-b3c1-7cb11d6e4edf.png)

Also see the relevant Twitch clip where it happened: https://clips.twitch.tv/HelpfulLongCardKevinTurtle-ogdZXCRdrPSod8YF

**Comment by rmarquis** [comment]
Yes, I've been investigating this very bug the past couple of hours (apparently due to a float to int conversion). I've found some other weirdness related to it too, but that one might be a vanilla bug. I'll open a new ticket shortly.

**Comment by rmarquis** [comment]
That particular issue happens because the game was stopped prior to 2nd round. You can see the whole match [here](https://www.twitch.tv/videos/1175605831), and players wait for their teammate around the 14:50 mark.

The delta time should be 4:52 - 4:08 = 44 sec, but it is  ~40 seconds too long (1:24) and that matches the extra wait time (14:52 to 15:32, ~40 sec, plus an extra ~3 sec of warmup). The countdown on the client side needs to take that wait time into account.

There's another minor issue but I'll treat it separately in a new ticket.

**Comment by jackeri** [comment]
Can this be closed? Is there something still to do?

**Comment by rmarquis** [comment]
Yes, closing now.
